'''

    TheKeyMachine - Animation Toolset for Maya Animators                                           
                                                                                                                                              
                                                                                                                                              
    This file is part of TheKeyMachine, an open source software for Autodesk Maya licensed under the GNU General Public License v3.0 (GPL-3.0).                                           
    You are free to use, modify, and distribute this code under the terms of the GPL-3.0 license.                                              
    By using this code, you agree to keep it open source and share any modifications.                                                          
    This code is provided "as is," without any warranty. For the full license text, visit https://www.gnu.org/licenses/gpl-3.0.html

    thekeymachine.xyz / x@thekeymachine.xyz                                                                                                                                        
                                                                                                                                              
    Developed by: Rodrigo Torres / rodritorres.com                                                                                             
                                                                                                                                             


'''

# TKM StyleSheet

QMenu_bg_color = "#333"
QMenu_border_color = "#333"
QMenu_border_size = "0px"
QMenu_padding_size = "2px"

QMenu_item_bg_color = "#333"
QMenu_item_border_color = "#333"
QMenu_item_border_size = "0px"
QMenu_item_padding_v_size = "7px"
QMenu_item_padding_h_size = "35px"

# ______________________________________________ Tool Bar style _______________________________________________ #

QMenu_bg_color = "#232323"
QMenu_padding_size = "0px"
customGraph_BG_color = "#202125"
customGraph_FG_color = "#323232"

# ______________________________________________ Text Translation _______________________________________________ #

# 全面的中文翻译字典
chinese_translation = {
    # 通用界面元素
    "Small": "小",
    "Medium": "中",
    "Big": "大",
    "Reload": "重新加载",
    "Open config file": "打开配置文件",
    "Reload menu": "重新加载菜单",
    "Cancel": "取消",
    "OK": "确定",
    "Help": "帮助",
    "Apply": "应用",
    "Save": "保存",
    "Load": "加载",
    "Edit": "编辑",
    "Delete": "删除",
    "Select": "选择",
    "Create": "创建",
    "Remove": "移除",
    "Show": "显示",
    "Hide": "隐藏",
    "Options": "选项",
    "Settings": "设置",
    "Preferences": "首选项",
    "Tools": "工具",
    "File": "文件",
    "New": "新建",
    "Open": "打开",
    "Import": "导入",
    "Export": "导出",
    "Close": "关闭",
    
    # 工具栏和菜单
    "SET": "选集",
    "Export Sets": "导出选集",
    "Import Sets": "导入选集",
    "Rename Group": "重命名组",
    "Export Group": "导出组",
    "Delete Group": "删除组",
    "Add Selection": "添加选择",
    "Remove Selection": "移除选择",
    "Change Color": "更改颜色",
    "Rename Set": "重命名选集",
    "Delete Set": "删除选集",
    "Selector": "选择器",
    "Move to ...": "移动到...",
    
    # 书签界面
    "Bookmarks": "书签",
    "Down one level": "降一级",
    "Create": "创建",
    "Remove": "移除",
    "Isolate": "隔离",
    "Open isolate bookmarks window": "打开隔离书签窗口",
    
    # 工具菜单
    "Mirror to opposite": "镜像到对面",
    "Add Excepction Invert": "添加反转例外",
    "Add Excepction Keep": "添加保持例外",
    "Remove Exception": "移除例外",
    "Copy Animation": "复制动画",
    "Paste Animation": "粘贴动画",
    "Copy Pose": "复制姿势",
    "Paste Pose": "粘贴姿势",
    "Paste at current frame": "粘贴到当前帧",
    "Paste selected keys only": "仅粘贴所选关键帧",
    "Mirror Animation": "镜像动画",
    "Clear All Saved Data": "清除所有保存的数据",
    
    # 相机工具
    "Select temp locators": "选择临时定位器",
    "Remove temp locators": "移除临时定位器",
    "Remove followCam": "移除跟随相机",
    "Create locator on selected": "在选择上创建定位器",
    "Create locator at selected offset": "在选择的偏移处创建定位器",
    "Create locator at origin": "在原点创建定位器",
    "Create followCam": "创建跟随相机",
    "Update followCam constraint": "更新跟随相机约束",
    
    # 链接对象
    "Copy Link Position": "复制链接位置",
    "Paste Link Position": "粘贴链接位置",
    "Auto-link": "自动链接",
    "Link Objects": "链接对象",
    "Add Link Objects": "添加链接对象",
    "Remove Link Objects": "移除链接对象",
    
    # 混合UI
    "Blend": "混合",
    "Blend to Default": "混合到默认",
    "Blend to Frame": "混合到关键帧",
    "Pull / Push": "拉/推",
    
    # UI标签
    "PP": "拉推",
    "BL": "混合",
    "BD": "默认",
    "BK": "帧混",
    "T": "处理",
    "TW": "补间",
    "TL": "补帧",
    
    # barMod 工具
    "Set Key": "设置关键帧",
    "Clear Key": "清除关键帧",
    "Step Forward": "前进一步",
    "Step Backward": "后退一步",
    "Next Key": "下一关键帧",
    "Previous Key": "上一关键帧",
    "Align Objects": "对齐对象",
    "Reset Values": "重置值",
    "Reset Selected": "重置选择",
    "Reset All": "重置全部",
    "Smart Constraint": "智能约束",
    "Parent": "父级",
    "Point": "点",
    "Orient": "方向",
    "Scale": "缩放",
    "Aim": "瞄准",
    "Refresh": "刷新",
    "Show/Hide": "显示/隐藏",
    "Select offset node": "选择偏移节点",
    "Style": "样式",
    "Move Keys": "移动关键帧",
    "Scale Keys": "缩放关键帧",
    "Offset Keys": "偏移关键帧",
    "Simplify Curves": "简化曲线",
    "Layer": "层",
    "Rotate": "旋转",
    "Translate": "平移",
    "Mirror": "镜像",
    "Flip": "翻转",
    "Swap": "交换",
    "Reverse": "反转",
    "Keyframe": "关键帧",
    "Frame": "帧",
    "Animation": "动画",
    "Channel Box": "通道盒",
    "Attribute Editor": "属性编辑器",
    "Graph Editor": "图表编辑器",
    "Time Editor": "时间编辑器",
    "Dope Sheet": "动画表编辑器",
    
    # keyToolsMod 工具
    "reBlock": "重新块",
    "Share Keys": "共享关键帧",
    "Block Keys": "块关键帧",
    "Unblock Keys": "解块关键帧",
    "Key Selection": "关键帧选择",
    "Key All": "全部关键帧",
    "Key Visible": "可见关键帧",
    "Key Modified": "修改关键帧",
    "Key Translate": "平移关键帧",
    "Key Rotate": "旋转关键帧",
    "Key Scale": "缩放关键帧",
    "Smart Key": "智能关键帧",
    "Auto Key": "自动关键帧",
    "Euler Filter": "欧拉滤波器",
    "Tween Machine": "补间机器",
    "Smooth": "平滑",
    "Linear": "线性",
    "Step": "步进",
    "Flat": "平坦",
    "Spline": "样条",
    "Clamped": "钳制",
    "Plateau": "平台",
    "Auto": "自动",
    "Clean Curves": "清理曲线",
    "Infinity": "无限",
    "Overshoot": "超调",
    
    # helperMod 工具
    "Clean up scene": "清理场景",
    "Delete unused nodes": "删除未使用节点",
    "Delete construction history": "删除构建历史",
    "Fix broken connections": "修复断开的连接",
    "Optimize scene": "优化场景",
    "Reduce file size": "减小文件大小",
    "Import reference": "导入引用",
    "Fix namespace": "修复命名空间",
    "Rename objects": "重命名对象",
    "Find and replace": "查找和替换",
    "Delete by type": "按类型删除",
    
    # uiMod 窗口和对话框
    "Donate": "捐赠",
    "About": "关于",
    "Report Bug": "报告错误",
    "Settings": "设置",
    "Support": "支持",
    "License": "许可证",
    "Version": "版本",
    "Update": "更新",
    "Installation": "安装",
    "Configuration": "配置",
    "Preferences": "首选项",
    "Help": "帮助",
    "Documentation": "文档",
    "Tutorials": "教程",
    "Quick Start": "快速开始",
    "User Guide": "用户指南",
    "Shortcuts": "快捷键",
    "Hotkeys": "热键",
    "Website": "网站",
    "Contact": "联系",
    "FAQ": "常见问题",
    "Credits": "制作人员",
    "Acknowledgements": "致谢",
    "Changelog": "更新日志",
    
    # selSetsMod 工具
    "Set Groups": "设置组",
    "Main": "主要",
    "New Set Group": "新建设置组",
    "Rename Set Group": "重命名设置组",
    "Delete Set Group": "删除设置组",
    "New Selection Set": "新建选择集",
    "Add to Selection Set": "添加到选择集",
    "Remove from Selection Set": "从选择集移除",
    "Select All Items": "选择所有项目",
    "Deselect All": "取消全选",
    "Toggle Visibility": "切换可见性",
    "Show All": "显示全部",
    "Hide All": "隐藏全部",
    "Gray": "灰色",
    "Yellow": "黄色",
    "Blue": "蓝色",
    "Dark Blue": "深蓝色",
    "Purple": "紫色",
    "Green": "绿色",
    "Light Red": "浅红色",
    "Dark Red": "深红色",
    
    # 窗口标题和提示
    "TheKeyMachine": "动画键控机",
    "Animation Toolset": "动画工具集",
    "Maya Animator": "Maya动画师",
    "Success": "成功",
    "Error": "错误",
    "Warning": "警告",
    "Information": "信息",
    "Confirmation": "确认",
    "Please Wait": "请稍候",
    "Processing": "处理中",
    "Loading": "加载中",
    "Saving": "保存中",
    "Completed": "已完成",
    "Failed": "失败",
    "Not Found": "未找到",
    "Already Exists": "已存在",
    "Invalid Input": "无效输入",
    "Permission Denied": "权限被拒绝",
    "File Not Found": "文件未找到",
    "Directory Not Found": "目录未找到",
    "Out of Memory": "内存不足",
    "Timeout": "超时",
    "Connection Failed": "连接失败",
    "Unable to Connect": "无法连接",
    "Server Error": "服务器错误",
    "Client Error": "客户端错误",
    "Network Error": "网络错误",
    "Unexpected Error": "意外错误",
    "Internal Error": "内部错误",
    "Unknown Error": "未知错误",
    
    # 新增：Graph Editor相关
    "Tangent": "切线",
    "Auto Tangent": "自动切线",
    "Spline Tangent": "样条切线",
    "Linear Tangent": "线性切线",
    "Flat Tangent": "平坦切线",
    "Step Tangent": "步进切线",
    "Plateau Tangent": "平台切线",
    "Clamped Tangent": "钳制切线",
    "Custom Tangent": "自定义切线",
    "In Tangent": "入切线",
    "Out Tangent": "出切线",
    "Both Tangents": "双切线",
    "Weighted Tangent": "权重切线",
    "Bake Animation": "烘焙动画",
    "Filter Curves": "过滤曲线",
    "Buffer Curves": "缓冲曲线",
    "Delete Static Channels": "删除静态通道",
    "Simplify": "简化",
    "Resample": "重采样",
    "Freshen": "刷新",
    "Zero Key": "零关键帧",
    "Extremes": "极值",
    "Breakdown": "中间帧",
    "Hold": "保持",
    "Ease": "缓动",
    "Ease In": "缓入",
    "Ease Out": "缓出",
    "Pre Infinity": "前无限",
    "Post Infinity": "后无限",
    "Constant": "常量",
    "Cycle": "循环",
    "Cycle with offset": "偏移循环",
    "Oscillate": "振荡",
    "Linear": "线性",
    "Match": "匹配",
    "Clamp": "钳制",
    "Noise": "噪声",
    "Jitter": "抖动",
    "Reset All": "重置全部",
    "Synchronize": "同步",
    "Synchronize Graph Editor": "同步图表编辑器",
    "Filter on Selected": "过滤所选",
    "Show All": "显示全部",
    "Show None": "不显示",
    "Show Connected": "显示已连接",
    "Show Animated": "显示已动画",
    
    # 新增：自定义工具特定文本
    "Create Shelf Icon": "创建工具架图标",
    "Change icon size": "更改图标大小",
    "Show Tooltips": "显示工具提示",
    "New Selection Set": "新建选择集",
    "New Group": "新建组",
    "Rename Set Group": "重命名设置组",
    "Please enter a valid set group name.": "请输入有效的设置组名称。",
    "A set group named": "一个名为",
    "already exists. Please choose a different name.": "的设置组已存在。请选择其他名称。",
    "Set group name cannot start with a number.": "设置组名称不能以数字开头。",
    "Set group name contains invalid characters or spaces. Only letters, numbers, and underscores are allowed.": "设置组名称包含无效字符或空格。只允许字母、数字和下划线。",
    "Cannot rename set group 'main'.": "无法重命名'main'设置组。",
    "Select Frame": "选择帧",
    "Current Frame": "当前帧",
    "Previous Frame": "上一帧",
    "Next Frame": "下一帧",
    "Playback": "播放",
    "Play Animation": "播放动画",
    "Stop Animation": "停止动画",
    "Play Forward": "向前播放",
    "Play Backward": "向后播放",
    "Snap to Frame": "对齐到帧",
    "Time Snap": "时间对齐",
    "Pivot Point": "轴心点",
    "World Space": "世界空间",
    "Local Space": "局部空间",
    "Object Space": "对象空间",
    "Parent Space": "父级空间",
    "Component Space": "组件空间",
    "Normal Space": "法线空间",
    "UV Space": "UV空间",
    "Screen Space": "屏幕空间",
    "Gimbal Space": "万向节空间",
    "Custom Space": "自定义空间",
    "Reset Zoom": "重置缩放",
    "Move All Keys": "移动所有关键帧",
    "Move Selected Keys": "移动选中关键帧",
    "Move and Scale Keys": "移动和缩放关键帧",
    "Sync with Channel Box": "与通道盒同步",
    "Click to toggle": "点击切换",
    "Drag to adjust": "拖动调整",
    "Right-click for options": "右键点击查看选项",
    "Adding exception": "添加例外",
    "Removing exception": "移除例外",
    "Select at least one object": "至少选择一个对象",
    "Nothing selected": "未选择任何内容",
    "No animation found": "未找到动画",
    "Animation copied": "已复制动画",
    "Animation pasted": "已粘贴动画",
    "Pose copied": "已复制姿势",
    "Pose pasted": "已粘贴姿势",
    "Reset completed": "重置完成",
    "Data cleared": "数据已清除",
    "Tracer created": "跟踪器已创建",
    "Tracer removed": "跟踪器已移除",
    "Follow camera created": "跟随相机已创建",
    "Follow camera removed": "跟随相机已移除",
    "Constraint created": "约束已创建",
    "Constraint removed": "约束已移除",
    "Align completed": "对齐完成",
    "Bookmark created": "书签已创建",
    "Bookmark removed": "书签已移除",
    "Isolating selection": "隔离选择",
    "Showing all": "显示全部",
    "Invalid selection": "无效选择",
    "No keys to move": "没有可移动的关键帧",
    "Keys moved": "关键帧已移动",
    "Keys scaled": "关键帧已缩放",
    "Curve simplified": "曲线已简化",
    "Cannot connect to server": "无法连接到服务器",
    "Update available": "有可用更新",
    "Up to date": "已是最新版本",
    "Download and install": "下载并安装",
    "Skip this version": "跳过此版本",
    "Remind me later": "稍后提醒我",
    "Please restart Maya": "请重启Maya",
    "Installation completed": "安装完成",
    "Update failed": "更新失败",
    "No update available": "没有可用更新",
    "Checking for updates": "检查更新中",
    "Unable to check for updates": "无法检查更新",
    "Please check your internet connection": "请检查网络连接",
    "License activated": "许可证已激活",
    "License expired": "许可证已过期",
    "Invalid license": "无效许可证",
    "Trial period": "试用期",
    "Trial expired": "试用期已过",
    "Days remaining": "剩余天数",
    "Unlimited access": "无限制访问",
    "Commercial use": "商业使用",
    "Educational use": "教育使用",
    "Personal use": "个人使用",
    "Enter license key": "输入许可证密钥",
    "Activate license": "激活许可证",
    "Deactivate license": "停用许可证",
    "Buy license": "购买许可证",
    "Extend license": "延长许可证",
    "Plugin loaded": "插件已加载",
    "Plugin unloaded": "插件已卸载",
    "Cannot load plugin": "无法加载插件",
    "Cannot unload plugin": "无法卸载插件",
    "Missing dependencies": "缺少依赖项",
    "Version conflict": "版本冲突",
    "Import successful": "导入成功",
    "Export successful": "导出成功",
    "Import failed": "导入失败",
    "Export failed": "导出失败",
    "File not found": "文件未找到",
    "Invalid file format": "无效文件格式",
    "Unsupported file type": "不支持的文件类型",
    "Operation cancelled": "操作已取消",
    "Operation completed": "操作已完成",
    "Operation failed": "操作失败",
    "Undo": "撤销",
    "Redo": "重做",
    "Cut": "剪切",
    "Copy": "复制",
    "Paste": "粘贴",
    "Find": "查找",
    "Replace": "替换",
    "Find and Replace": "查找并替换",
    "Go to Frame": "转到帧",
    "Frame Range": "帧范围",
    "Start Frame": "起始帧",
    "End Frame": "结束帧",
    "Set Range": "设置范围",
    "Auto Frame All": "自动全部帧",
    "Auto Frame Selected": "自动选中帧",
    "Fit View": "适应视图",
    "Reset View": "重置视图",
    "Pan View": "平移视图",
    "Zoom View": "缩放视图",
    "Rotate View": "旋转视图",
    "Camera Settings": "相机设置",
    "Display Settings": "显示设置",
    "Grid Settings": "网格设置",
    "Show Grid": "显示网格",
    "Show Axes": "显示坐标轴",
    "Show Frame Numbers": "显示帧数",
    "Show Time Code": "显示时间码",
    "Show Curves": "显示曲线",
    "Show Handles": "显示手柄",
    "Show Tangents": "显示切线",
    "Show Values": "显示值",
    "Show Labels": "显示标签",
    "Auto Scale": "自动缩放",
    "Normalize": "归一化",
    "Stack Curves": "堆叠曲线",
    "Separate Curves": "分离曲线",
    "Reset Graph": "重置图表",
    "Fit All Curves": "适应所有曲线",
    "Fit Selected Curves": "适应选中曲线",
    "Curves Visibility": "曲线可见性",
    "Background Color": "背景颜色",
    "Curve Color": "曲线颜色",
    "Handle Color": "手柄颜色",
    "Grid Color": "网格颜色",
    "Label Color": "标签颜色",
    "Selection Color": "选择颜色",
    "Highlight Color": "高亮颜色",
    "Default Settings": "默认设置",
    "Custom Settings": "自定义设置",
    "Save Settings": "保存设置",
    "Load Settings": "加载设置",
    "Reset Settings": "重置设置",
    "User Preferences": "用户首选项",
    "Global Settings": "全局设置",
    "Project Settings": "项目设置",
    "Scene Settings": "场景设置",
    "Tool Settings": "工具设置",
    "Layout Settings": "布局设置",
    "Appearance": "外观",
    "Behavior": "行为",
    "Performance": "性能",
    "Advanced": "高级",
    "Default": "默认",
    "Interface": "界面",
    "Theme": "主题",
    "Dark Theme": "深色主题",
    "Light Theme": "浅色主题",
    "Custom Theme": "自定义主题",
    "Icon Size": "图标大小",
    "Font Size": "字体大小",
    "Tooltip Delay": "工具提示延迟",
    "Language": "语言",
    "English": "英语",
    "Chinese": "中文",
    "Spanish": "西班牙语",
    "French": "法语",
    "German": "德语",
    "Japanese": "日语",
    "Korean": "韩语",
    "Russian": "俄语",
    "Portuguese": "葡萄牙语",
    "Italian": "意大利语",
    "Startup": "启动",
    "Auto Load": "自动加载",
    "Auto Save": "自动保存",
    "Auto Backup": "自动备份",
    "Welcome Screen": "欢迎界面",
    "Recent Files": "最近文件",
    "Splash Screen": "启动画面",
    "Confirm on Exit": "退出时确认",
    "Submit Bug Report": "提交错误报告",
    "Report an Issue": "报告问题",
    "Send Feedback": "发送反馈",
    "Contact Support": "联系支持",
    "Visit Website": "访问网站",
    "Check for Updates": "检查更新",
    "About TheKeyMachine": "关于TheKeyMachine",
    "Online Documentation": "在线文档",
    "Video Tutorials": "视频教程",
    "Forum": "论坛",
    "Community": "社区",
    "Discord": "Discord",
    "Social Media": "社交媒体",
    "Facebook": "Facebook",
    "Twitter": "Twitter",
    "Instagram": "Instagram",
    "YouTube": "YouTube",
    "LinkedIn": "LinkedIn",
    "Rename Set": "重命名设置",
    "Please enter a valid set name.": "请输入有效的设置名称。",
    "A set named": "一个名为",
    "already exists. Please choose a different name.": "的设置已存在。请选择其他名称。",
    "Set name cannot start with a number.": "设置名称不能以数字开头。",
    "Set name contains invalid characters or spaces. Only letters, numbers, and underscores are allowed.": "设置名称包含无效字符或空格。只允许字母、数字和下划线。",
    "Set Items": "设置项目",
    "Select Items": "选择项目",
    "Set Selection": "设置选择",
    "Change Selection": "更改选择",
    "Add to Selection": "添加到选择",
    "Remove from Selection": "从选择中移除",
    "Clear Selection": "清除选择",
    "Invert Selection": "反转选择",
    "Select All": "全选",
    "Select None": "取消全选",
    "Select by Type": "按类型选择",
    "Select Connected": "选择已连接",
    "Select Similar": "选择相似",
    "Selection Filter": "选择过滤器",
    "Selection Mask": "选择蒙版",
    "Selection Set": "选择集合",
    "Selection Group": "选择组",
    "Selection List": "选择列表",
    "Selection Order": "选择顺序",
}

def translate(text):
    """返回文本的中文翻译，如果没有翻译则返回原文本"""
    return chinese_translation.get(text, text) 