from __future__ import absolute_import, division, print_function, unicode_literals

TOOLS_FOLDER = "tools"

RECOMMENDED_TOOLS = [
    ("cube", "#8A5A5A", "Delete Redundant Keys", 
     {'script_file': 'DeleteRedundantKeys.py'}),
    ("cube", "#5A8AB5", "Align Objects", 
     {'script_file': 'AlignObjects.py'}),
    ("eye", "#6A9A7A", "Animation Visibility Mode", 
     {'script_file': 'AnimationVisibilityMode.py'}),
    ("rocket", "#9A6A6A", "Clear Animation", 
     {'script_file': 'ClearAnimation.py'}),
    ("cube", "#8A7A6A", "Crop Animation", 
     {'script_file': 'CropAnimation.py'}),
    ("lightning", "#7A8A5A", "Fast Bake", 
     {'script_file': 'FastBake.py'}),
    ("play", "#5A9A7A", "Nudge Left", 
     {'script_file': 'NudgeLeft.py'}),
    ("play", "#5A9A7A", "Nudge Right", 
     {'script_file': 'NudgeRight.py'}),
    ("star", "#5A9A5A", "Reset Pose", 
     {'script_file': 'ResetPose.py'}),
    ("heart", "#7A8A7A", "Share Keys", 
     {'script_file': 'ShareKeys.py'}),
    ("gear", "#8A6A8A", "Sliders Pop Up", 
     {'script_file': 'SlidersPopup.py'}),
    ("diamond", "#5A8A9A", "Smart Go to Next Frame", 
     {'script_file': 'SmartGoToNextFrame.py'}),
    ("diamond", "#5A8A9A", "Smart Go To Next Key", 
     {'script_file': 'SmartGoToNextKey.py'}),
    ("diamond", "#5A8A9A", "Smart Go to Next Keyframe", 
     {'script_file': 'SmartGoToNextKey.py'}),
    ("diamond", "#6A7A9A", "Smart Go to Previous Frame", 
     {'script_file': 'SmartGoToPreviousFrame.py'}),
    ("diamond", "#6A7A9A", "Smart Go to Previous Keyframe", 
     {'script_file': 'SmartGoToPreviousKeyframe.py'}),
    ("cube", "#7A6A9A", "Smart Snap Keys", 
     {'script_file': 'SmartSnapKeys.py'}),
    ("cube", "#6A8A8A", "Toggle Geometry", 
     {'script_file': 'ToggleGeometry.py'}),
    ("camera", "#7A7A9A", "Toggle Imageplane", 
     {'script_file': 'ToggleImageplanes.py'}),
    ("target", "#8A8A6A", "Toggle Locator", 
     {'script_file': 'ToggleLocator.py'}),
    ("graph", "#6A9A8A", "Toggle Wireframe Mode", 
     {'script_file': 'ToggleWireframeMode.py'}),
    ("eye", "#9A7A8A", "Toggle XRay Mode", 
     {'script_file': 'ToggleXrayMode.py'}),
]
