# uncompyle6 version 3.8.0
# Python bytecode 2.7 (62211)
# Decompiled from: Python 3.10.2 (tags/v3.10.2:a58ebcc, Jan 17 2022, 14:12:15) [MSC v.1929 64 bit (AMD64)]
# Embedded file name: F:/Maya_Projects\sat\aboutWindow.py
# Compiled at: 2016-11-26 19:42:10
from .Qt import QtCore, QtWidgets, QtGui

class Ui_Dialog(object):

    def setupUi(self, Dialog):
        Dialog.setObjectName('Dialog')
        Dialog.resize(210, 190)
        Dialog.setMinimumSize(QtCore.QSize(210, 190))
        Dialog.setMaximumSize(QtCore.QSize(210, 190))
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName('verticalLayout')
        self.label = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName('label')
        self.verticalLayout.addWidget(self.label)
        self.label_5 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setWordWrap(True)
        self.label_5.setObjectName('label_5')
        self.verticalLayout.addWidget(self.label_5)
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setObjectName('frame')
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setContentsMargins(5, 2, 5, 5)
        self.verticalLayout_2.setObjectName('verticalLayout_2')
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName('label_2')
        self.verticalLayout_2.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName('label_3')
        self.verticalLayout_2.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setWordWrap(True)
        self.label_4.setObjectName('label_4')
        self.verticalLayout_2.addWidget(self.label_4)
        self.verticalLayout.addWidget(self.frame)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout.setObjectName('horizontalLayout')
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setObjectName('pushButton')
        self.horizontalLayout.addWidget(self.pushButton)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtWidgets.QApplication.translate('Dialog', 'About', None))
        self.label.setText(QtWidgets.QApplication.translate('Dialog', 'Shape Animation Tool', None))
        self.label_5.setText(QtWidgets.QApplication.translate('Dialog', 'Version 2.0', None))
        self.label_2.setText(QtWidgets.QApplication.translate('Dialog', 'Tool, for correct shape of geometry in animation.', None))
        self.label_3.setText(QtWidgets.QApplication.translate('Dialog', 'Tool - Pavel Korolyov', None))
        self.label_4.setText(QtWidgets.QApplication.translate('Dialog', 'Brush - Brave Rabbit Studio', None))
        self.pushButton.setText(QtWidgets.QApplication.translate('Dialog', 'Close', None))
        return