global string $gShelfTopLevel;
string $currentShelf = `tabLayout -q -st $gShelfTopLevel`;
string $rootPath=`InstallLocationPath`;
string $iconsPath=$rootPath+"icons/mirror_tool.bmp";
string $source_path="source \"" + $rootPath + "mirror_walk_tool_code.mel\";";
string $ico_path_gl_string="global string $mirror_tool_icon_path = \"" + $iconsPath  + "\";";

shelfButton
   	-command ($source_path + "\n" + $ico_path_gl_string + "\nMirror_tool_menue;")
    -annotation "This tool helps you make walking and running animations. It makes a mirror copy of the movement with a time shift by a specified amount of time"
    -label ""
    -imageOverlayLabel ""
    -image ($iconsPath )
	-hi ($iconsPath )
    -sourceType "mel"
    -parent $currentShelf;


global proc string InstallLocationPath ()
{
    string $whatIs=`whatIs InstallLocationPath`;
    string $fullPath=`substring $whatIs 25 999`;
    string $buffer[];
    int $numTok=`tokenize $fullPath "/" $buffer`;
    int $numLetters=size($fullPath);
    int $numLettersLastFolder=size($buffer[$numTok-1]);
    string $scriptLocation=`substring $fullPath 1 ($numLetters-$numLettersLastFolder)`;
    return $scriptLocation;
}

