//大QC
global proc bbstg_bb_QC_allQC(int $mode)
{
    scrollField -e -clear bb_QC_informationSF;
    if($mode == 0){
        if(`checkBox -q -v bb_QC_unkonwCB`) bbstg_bb_QC_unkownQC;
        if(`checkBox -q -v bb_QC_intermediaCB`) bbstg_bb_QC_intermediaObjQC;
        if(`checkBox -q -v bb_QC_noVertexCB`) bbstg_bb_QC_zeroVertexObjQC;
        if(`checkBox -q -v bb_QC_soundCB`) bbstg_bb_QC_audioQC;
    }
    if($mode == 1){
        if(`checkBox -q -v bb_QC_renameCB`) bbstg_bb_QC_repeatedNameQC;
        if(`checkBox -q -v bb_QC_modleSuffixCB`) bbstg_bb_QC_modleSuffixQC;
        if(`checkBox -q -v bb_QC_modleLockCB`) bbstg_bb_QC_attrLockQC;
        if(`checkBox -q -v bb_QC_modleVisCB`) bbstg_bb_QC_modleVisQC;
        if(`checkBox -q -v bb_QC_lightCB`) bbstg_bb_QC_lightQC;
        if(`checkBox -q -v bb_QC_camCB`) bbstg_bb_QC_camQC;
        if(`checkBox -q -v bb_QC_ctrlValueCB`) bbstg_bb_QC_ctrlValueQC;
        if(`checkBox -q -v bb_QC_faceMappingCB`) bbstg_bb_QC_faceMappingQC;
        if(`checkBox -q -v bb_QC_animKeyCB`) bbstg_bb_QC_animKeyQC;
        if(`checkBox -q -v bb_QC_layerCB`) bbstg_bb_QC_layerQC;
        if(`checkBox -q -v bb_QC_smoothCB`) bbstg_bb_QC_smoothQC;
        if(`checkBox -q -v bb_QC_unusedCB`) bbstg_bb_QC_unusedQC;
    }
}

//建立set
global proc bbstg_bb_QC_sets(string $setName,string $setElement[])
{
    if(`objExists $setName`) delete $setName;
    select -cl;
    sets -n $setName;
    sets -addElement $setName $setElement;
}
//输出信息
global proc bbstg_bb_QC_informationOutput(int $checkItem,int $conclusion,int $setNum,string $setName)
{
    string $checkOk[] = {"Unkown 检查---------------------------OK！！！",
                         "Intremedia Obj 检查-------------------OK！！！",
                         "无顶点模型 检查-------------------------OK！！！",
                         "声音 检查------------------------------OK！！！",
                         "Polygons重命名 检查--------------------OK！！！",
                         "Surfaces重命名 检查--------------------OK！！！",
                         "Curves重命名 检查----------------------OK！！！",
                         "Joint重命名 检查-----------------------OK！！！",
                         "模型后缀 检查---------------------------OK！！！",
                         "模型锁属性 检查-------------------------OK！！！",
                         "模型显示 检查---------------------------OK！！！",
                         "灯光 检查------------------------------OK！！！",
                         "摄像机 检查----------------------------OK！！！",
                         "控制器数值 检查-------------------------OK！！！",
                         "选面贴 检查----------------------------OK！！！",
                         "动画帧 检查----------------------------OK！！！",
                         "显示层 检查----------------------------OK！！！",
                         "Smooth添加 检查------------------------OK！！！",
                         "Smooth位置 检查------------------------OK！！！",
                         "Smooth连接 检查------------------------OK！！！",
                         "无影响骨骼 检查-------------------------OK！！！"};
    string $checkNoPass[] = {"Unkown 检查：","Intremedia Obj 检查：","无顶点模型 检查：","声音 检查：",
                             "Polygons重命名 检查：","Surfaces重命名 检查：","Curves重命名 检查：","Joint重命名 检查：",
                             "模型后缀 检查：","模型锁属性 检查：","模型显示 检查：","灯光 检查：","摄像机 检查：",
                             "控制器数值 检查：","选面贴 检查：","动画帧 检查：","显示层 检查：",
                             "Smooth添加 检查：","Smooth位置 检查：","Smooth连接 检查：","无影响骨骼 检查："};
    string $information;
    if($conclusion == 0){
        $information = $checkNoPass[$checkItem] + " 有 " + $setNum +
                       " 个物体未通过，已Set到 " +  $setName + " 。\n\n";
    }
    else if($conclusion == 1){
        $information = $checkOk[$checkItem] + "\n\n";;
    }
    scrollField -e -insertText $information bb_QC_informationSF;
}
//deleteFix
global proc bbstg_bb_QC_deleteFix(string $setName)
{
    if(`objExists $setName`){
        string $delete[] = `sets -q $setName`;
        for($i=0;$i<size($delete);$i++){
            if(`objExists $delete[$i]`)
                lockNode -lock off $delete[$i];
                delete $delete[$i];
        }
    }
    else{
        bbstg_bb_QC_noneQC;
    }
}
//提示先QC
global proc bbstg_bb_QC_noneQC()
{
    string $information[] = {"你得先QC啊！！","没有可修改的物体！！","都没有QC，怎么修改，囧！！",
                          "点了QC再来点我！！"};
    int $i = `rand 0 (size($information))`;
    scrollField -e -insertText ($information[$i]+"\n\n") bb_QC_informationSF;
}
//set应用
global proc bbstg_bb_QC_setApply(string $setObj[],string $setName,int $list)
{
    int $nums = size($setObj);
    if($nums != 0){
        bbstg_bb_QC_informationOutput($list,0,$nums,$setName);
        bbstg_bb_QC_sets($setName,$setObj);
    }
    else{
        bbstg_bb_QC_informationOutput($list,1,0,"");
    }
}
//shape找transforms
global proc string[] bbstg_bb_QC_shapes2transforms(string $shapeType)
{
    string $shapes[] = `ls -l -type $shapeType`;
    string $obj[];
    for($i=0;$i<size($shapes);$i++){
        string $transforms[] = `listRelatives -f -p $shapes[$i]`;
        $obj[size($obj)] = $transforms[0];
    }
    $obj = stringArrayRemoveDuplicates($obj);
    return $obj;
}

//------------------------------unkown------------------------------//
global proc bbstg_bb_QC_unkownQC()
{
    string $unkownNode[] = `ls -type "unknown"`;
    bbstg_bb_QC_setApply($unkownNode,"QC_unkownSets",0);
}

//------------------------------intermedia Obj------------------------------//
global proc bbstg_bb_QC_intermediaObjQC()
{
    if(`objExists "QC_intermediaObjSets"`) delete "QC_intermediaObjSets";
    string $allShapes[] = `ls -geometry`;
    int $inter;
    string $history[],$interObj[],$outMesh[];
    clear $interObj;
    for($i=0;$i<size($allShapes);$i++){
        $inter = `getAttr ($allShapes[$i] + ".intermediateObject")`;
        if($inter){
            $history = `listConnections -sh 1 $allShapes[$i]`;
            if(!size($history)){
                $interObj[size($interObj)] = $allShapes[$i];
            }
            if(`nodeType $allShapes[$i]` == "mesh"){
                $outMesh = `listConnections -sh 1 ($allShapes[$i] + ".outMesh")`;
                if(`attributeExists "inMesh" $outMesh[0]`){
                    if(!`isConnected ($allShapes[$i] + ".outMesh") ($outMesh[0] + ".inMesh")`){
                        $interObj[size($interObj)] = $allShapes[$i];
                    }
                }
            }
        }
    }
    bbstg_bb_QC_setApply($interObj,"QC_intermediaObjSets",1);
}


//------------------------------无顶点模型------------------------------//
global proc bbstg_bb_QC_zeroVertexObjQC()
{
    string $mesh[] = `ls -l -type "mesh"`;
    int $vtxNums[];
    string $obj[];
    for($i=0;$i<size($obj);$i++){
        $vtxNums = `polyEvaluate -v $mesh[$i]`;
        if($vtxNums[0] == 0){
            string $transforms[] = `listRelatives -f -p $mesh[$i]`;
            $obj[size($obj)] = $transforms[0];
        }
    }
    bbstg_bb_QC_setApply($obj,"QC_zeroVertexObjSets",2);
}

//------------------------------声音------------------------------//
global proc bbstg_bb_QC_audioQC()
{
    string $audioNode[] = `ls -l -type "audio"`;
    bbstg_bb_QC_setApply($audioNode,"QC_audioSets",3);
}
//------------------------------重命名------------------------------//
global proc bbstg_bb_QC_repeatedNameQC()
{
    int $ply = `checkBox -q -v bb_QC_renamePlyCB`;
    int $surf = `checkBox -q -v bb_QC_renameSurfCB`;
    int $curves = `checkBox -q -v bb_QC_renameCurvesCB`;
    int $joint = `checkBox -q -v bb_QC_renameJointCB`;

    string $repeated_ply[],$repeated_surf[],$repeated_cv[],$repeated_joint[];
    int $plyNum,$surfNum,$cvNum,$jointNum;
    if($ply == 1){
        if(`objExists "QC_reNameSets_Ply"`) delete "QC_reNameSets_Ply";
        string $obj[] = bbstg_bb_QC_shapes2transforms("mesh");
        $repeated_ply = bbstg_bb_QC_repeatedNameReturn("transform",$obj);
        bbstg_bb_QC_setApply($repeated_ply,"QC_reNameSets_Ply",4);
    }
    if($surf == 1){
        if(`objExists "QC_reNameSets_Surf"`) delete "QC_reNameSets_Surf";
        string $obj[] = bbstg_bb_QC_shapes2transforms("nurbsSurface");
        $repeated_surf = bbstg_bb_QC_repeatedNameReturn("transform",$obj);
        bbstg_bb_QC_setApply($repeated_surf,"QC_reNameSets_Surf",5);
    }
    if($curves == 1){
        if(`objExists "QC_reNameSets_Cv"`) delete "QC_reNameSets_Cv";
        string $obj[] = bbstg_bb_QC_shapes2transforms("nurbsCurve");
        $repeated_cv = bbstg_bb_QC_repeatedNameReturn("transform",$obj);
        bbstg_bb_QC_setApply($repeated_cv,"QC_reNameSets_Cv",6);
    }
    if($joint == 1){
        if(`objExists "QC_reNameSets_Joint"`) delete "QC_reNameSets_Joint";
        string $obj[] = `ls -l -type "joint"`;
        $repeated_joint = bbstg_bb_QC_repeatedNameReturn("joint",$obj);
        bbstg_bb_QC_setApply($repeated_joint,"QC_reNameSets_Joint",7);
    }
}

global proc string[] bbstg_bb_QC_repeatedNameReturn(string $nodeType,string $obj[])
{
    string $repeated[];
    for($i=0;$i<size($obj);$i++){
        string $constitute[] = stringToStringArray($obj[$i], "|");
        string $confirm[] = `ls -type $nodeType $constitute[size($constitute)-1]`;
        if(size($confirm) > 1){
            $repeated[size($repeated)] = $obj[$i];
        }
    }
    return $repeated;
}

global proc bbstg_bb_QC_repeatedNameFix()
{
    int $noneQC = 0;
    if(`objExists "QC_reNameSets_Ply"`){
        bbstg_bb_QC_repeatedNameFixApply("QC_reNameSets_Ply");
        $noneQC = 1;
    }
    if(`objExists "QC_reNameSets_Surf"`){
        bbstg_bb_QC_repeatedNameFixApply("QC_reNameSets_Surf");
        $noneQC = 1;
    }
    if(`objExists "QC_reNameSets_Cv"`){
        bbstg_bb_QC_repeatedNameFixApply("QC_reNameSets_Cv");
        $noneQC = 1;
    }
    if(`objExists "QC_reNameSets_Joint"`){
        bbstg_bb_QC_repeatedNameFixApply("QC_reNameSets_Joint");
        $noneQC = 1;
    }
    if($noneQC = 0) bbstg_bb_QC_noneQC;
}

global proc bbstg_bb_QC_repeatedNameFixApply(string $setName)
{
    string $allSetsObj[] = `sets -q $setName`;
    string $shorterList[];
    for($i=0;$i<size($allSetsObj);$i++){
        string $array[] = stringToStringArray($allSetsObj[$i], "|");
        $shorterList[size($shorterList)] = $array[size($array)-1];
    }
    $shorterList = stringArrayRemoveDuplicates($shorterList);
    for($i=0;$i<size($shorterList);$i++){
        string $sameObj[] = `ls $shorterList[$i]`;
        for($j=0;$j<size($sameObj);$j++){
            int $suffix = 1;
            string $rename;
            int $sameNums;
            do{
                $rename = $shorterList[$i] + $suffix;
                $suffix += 1;
                $sameNums = size(`ls $rename`);
            }while($sameNums == 1);
            rename $sameObj[$j] $rename;
        }
    }
}
//------------------------------模型后缀------------------------------//
global proc bbstg_bb_QC_modleSuffixQC()
{
    if(`objExists "QC_modleSuffixSets"`) delete "QC_modleSuffixSets";
    string $falseObj[] = bbstg_bb_QC_suffixQCApply("bb_QC_modleSuffixTF","mesh",0);
    bbstg_bb_QC_setApply($falseObj,"QC_modleSuffixSets",8);
}

//后缀QC应用
global proc string[] bbstg_bb_QC_suffixQCApply(string $textField,string $shapeType,int $returnType)
{
    string $suffixTx = `textField -q -tx $textField`;
    $suffixTx = substituteAllString($suffixTx, ",", " ");
    string $suffixArray[] = stringToStringArray($suffixTx, " ");
    string $obj[] = bbstg_bb_QC_shapes2transforms($shapeType);
    int $suffixNum = `checkBox -q -v bb_QC_suffixNumCB`;
    string $falseObj[],$trueObj[];
    for($i=0;$i<size($obj);$i++){
        int $true = 0;
        if(size($suffixArray)){
            for($j=0;$j<size($suffixArray);$j++){
                if(`gmatch $obj[$i] ("*"+$suffixArray[$j]+"*")`){
                    if(`gmatch $obj[$i] ("*"+$suffixArray[$j])`){
                        $true = 1;
                        $trueObj[size($trueObj)] = $obj[$i];
                        break;
                    }
                    else if($suffixNum == 0){
                        string $switch = substituteAllString($obj[$i], $suffixArray[$j], " ");
                        string $split[] = stringToStringArray($switch, " ");
                        if(isValidString($split[size($split)-1], "[0-9][0-9]*")){
                            $true = 1;
                            $trueObj[size($trueObj)] = $obj[$i];
                            break;
                        }
                    }
                }
            }
        }
        else{
            $true = 1;
            $trueObj[size($trueObj)] = $obj[$i];
        }
        if($true == 0){
            $falseObj[size($falseObj)] = $obj[$i];
        }
    }
    if($returnType == 0) return $falseObj;
    if($returnType == 1) return $trueObj;
}

//------------------------------模型锁属性------------------------------//
global proc bbstg_bb_QC_attrLockQC()
{
    if(`objExists "QC_attrLockSets"`) delete "QC_attrLockSets";
    string $obj[] = bbstg_bb_QC_suffixQCApply("bb_QC_modleSuffixTF","mesh",1);
    string $falseObj[];
    string $attr[] = {"tx", "ty", "tz", "rx", "ry", "rz", "sx", "sy", "sz"};
    for($i=0;$i<size($obj);$i++){
        for($j=0;$j<size($attr);$j++){
            int $lock = `getAttr -lock ($obj[$i] + "." + $attr[$j])`;
            if($lock == 0){
                $falseObj[size($falseObj)] = $obj[$i];
                break;
            }
        }
    }
    bbstg_bb_QC_setApply($falseObj,"QC_attrLockSets",9);
}

global proc bbstg_bb_QC_attrLockFix()
{
    if(`objExists "QC_attrLockSets"`){
        string $fixObj[] = `sets -q "QC_attrLockSets"`;
        for($i=0;$i<size($fixObj);$i++){
            string $attr[] = {"tx", "ty", "tz", "rx", "ry", "rz", "sx", "sy", "sz"};
            for($j=0;$j<size($attr);$j++){
                setAttr -lock 1 ($fixObj[$i] + "." + $attr[$j]);
            }
        }
    }
    else{
        bbstg_bb_QC_noneQC;
    }
}

//------------------------------模型显示------------------------------//
global proc bbstg_bb_QC_modleVisQC()
{
    if(`objExists "QC_modleVisSets"`) delete "QC_modleVisSets";
    string $obj[] = bbstg_bb_QC_shapes2transforms("mesh");
    string $trueObj[] = bbstg_bb_QC_suffixQCApply("bb_QC_modleSuffixTF","mesh",1);
    string $falseObj[] = bbstg_bb_QC_suffixQCApply("bb_QC_modleSuffixTF","mesh",0);
    string $setObj[];
    for($i=0;$i<size($obj);$i++){
        int $vis = `getAttr ($obj[$i] + ".v")`;
        int $keyable = `getAttr -keyable ($obj[$i] + ".v")`;
        string $connection[] = `listConnections -d off -s on ($obj[$i] + ".v")`;
        if(stringArrayContains($obj[$i], $trueObj)){
            if($vis==0 || $keyable==0 || size($connection)!=0)
                $setObj[size($setObj)] = $obj[$i];
        }
        else if(stringArrayContains($obj[$i], $falseObj)){
            if($vis==1){
                $setObj[size($setObj)] = $obj[$i];
            }
        }
    }
    bbstg_bb_QC_setApply($setObj,"QC_modleVisSets",10);
}

global proc bbstg_bb_QC_modleVisFix()
{
    if(`objExists "QC_modleVisSets"`){
        string $obj[] = `sets -q "QC_modleVisSets"`;
        string $trueObj[] = bbstg_bb_QC_suffixQCApply("bb_QC_modleSuffixTF","mesh",1);
        string $falseObj[] = bbstg_bb_QC_suffixQCApply("bb_QC_modleSuffixTF","mesh",0);
        for($i=0;$i<size($obj);$i++){
            int $vis = `getAttr ($obj[$i] + ".v")`;
            string $longName[] = `ls -l $obj[$i]`;
            if(stringArrayContains($longName[0], $trueObj)){
                setAttr -lock 0 ($obj[$i] + ".v");
                CBdeleteConnection ($obj[$i] + ".v");
                setAttr ($obj[$i] + ".v") 1;
            }
            else if(stringArrayContains($longName[0], $falseObj)){
                int $lock = `getAttr -lock ($obj[$i] + ".v")`;
                setAttr -lock 0 ($obj[$i] + ".v");
                CBdeleteConnection ($obj[$i] + ".v");
                setAttr ($obj[$i] + ".v") 0;
                if($lock == 1) setAttr -lock 1 ($obj[$i] + ".v");
            }
        }
    }
    else{
        bbstg_bb_QC_noneQC;
    }
}
//------------------------------灯光------------------------------//
global proc bbstg_bb_QC_lightQC()
{
    if(`objExists "QC_lightSets"`) delete "QC_lightSets";
    string $lightShapes[] = `ls -lights`;
    string $light[];
    for($i=0;$i<size($lightShapes);$i++){
        string $transforms[] = `listRelatives -f -p $lightShapes[$i]`;
        $light[size($light)] = $transforms[0];
    }
    bbstg_bb_QC_setApply($light,"QC_lightSets",11);
}
//------------------------------摄像机------------------------------//
global proc bbstg_bb_QC_camQC()
{
    if(`objExists "QC_cameraSets"`) delete "QC_cameraSets";
    string $cameras[] = bbstg_bb_QC_shapes2transforms("camera");
    string $cameraTx = `textField -q -tx bb_QC_camTF`;
    $cameraTx = substituteAllString($cameraTx, ",", " ");
    string $cameraArray[] = stringToStringArray($cameraTx, " ");
    $cameraArray = stringArrayCatenate($cameraArray, {"persp","top","front","side"});
    string $setObj[];
    for($i=0;$i<size($cameras);$i++){
        string $shortNames[] = stringToStringArray($cameras[$i], "|");
        if(!stringArrayContains($shortNames[size($shortNames)-1], $cameraArray)){
            $setObj[size($setObj)] = $cameras[$i];
        }
    }
    bbstg_bb_QC_setApply($setObj,"QC_cameraSets",12);
}
//------------------------------控制器数值------------------------------//
global proc bbstg_bb_QC_ctrlValueQC()
{
    if(`objExists "QC_ctrlValueSets"`) delete "QC_ctrlValueSets";
    string $ctrl[] = bbstg_bb_QC_suffixQCApply("bb_QC_ctrlSuffixTF","nurbsCurve",1);
    string $extraAttr[] = `textScrollList -q -allItems bb_QC_ctrlAttrTSL`;
    string $customAttr[] = {".tx 0",".ty 0",".tz 0",".rx 0",".ry 0",".rz 0",".sx 1",".sy 1",".sz 1",".v 1"};
    string $allAttr[] = stringArrayCatenate($customAttr, $extraAttr);
    string $extraCtrl[] = `textScrollList -q -allItems bb_QC_extraCtrlTSL`;
    string $setObj[];
    for($i=0;$i<size($ctrl);$i++){
        for($j=0;$j<size($allAttr);$j++){
            string $attrValue[] = stringToStringArray($allAttr[$j], " ");
            string $attrName = substituteAllString($attrValue[0], ".", "");
            if(`attributeExists $attrName $ctrl[$i]`){
                string $connections[] = `listConnections -d off -s on ($ctrl[$i]+$attrValue[0])`;
                if(`getAttr -k ($ctrl[$i]+$attrValue[0])` && !size($connections) && !`getAttr -l ($ctrl[$i]+$attrValue[0])`){
                    float $value = `getAttr ($ctrl[$i]+$attrValue[0])`;
                    float $aimValue = $attrValue[1];
                    if($value < ($aimValue-0.000001) || $value > ($aimValue+0.000001)){
                        $setObj[size($setObj)] = $ctrl[$i];
                        break;
                    }
                }
            }
        }
    }
    for($i=0;$i<size($extraCtrl);$i++){
        string $ctrlAttrValue[] = stringToStringArray($extraCtrl[$i], " ");
        string $ctrlAttr[] = stringToStringArray($ctrlAttrValue[0], ".");
        if(`attributeExists $ctrlAttr[1] $ctrlAttr[0]`){
            float $value = `getAttr $ctrlAttrValue[0]`;
            float $aimValue = $ctrlAttrValue[1];
            if($value < ($aimValue-0.000001) || $value > ($aimValue+0.000001)){
                $setObj[size($setObj)] = $ctrlAttr[0];
            }
        }
    }
    $setObj = stringArrayRemoveDuplicates($setObj);
    bbstg_bb_QC_setApply($setObj,"QC_ctrlValueSets",13);
}

global proc bbstg_bb_QC_ctrlValueFix()
{
    if(`objExists "QC_ctrlValueSets"`){
        string $ctrl[] = `sets -q "QC_ctrlValueSets"`;
        string $extraAttr[] = `textScrollList -q -allItems bb_QC_ctrlAttrTSL`;
        string $customAttr[] = {".tx 0",".ty 0",".tz 0",".rx 0",".ry 0",".rz 0",".sx 1",".sy 1",".sz 1",".v 1"};
        string $allAttr[] = stringArrayCatenate($customAttr, $extraAttr);
        string $extraCtrl[] = `textScrollList -q -allItems bb_QC_extraCtrlTSL`;

        for($i=0;$i<size($extraCtrl);$i++){
        string $ctrlAttrValue[] = stringToStringArray($extraCtrl[$i], " ");
        string $ctrlAttr[] = stringToStringArray($ctrlAttrValue[0], ".");
            if(`attributeExists $ctrlAttr[1] $ctrlAttr[0]`){
                float $value = $ctrlAttrValue[1];
                setAttr $ctrlAttrValue[0] $value;
            }
        }

        for($i=0;$i<size($ctrl);$i++){
            for($j=0;$j<size($allAttr);$j++){
                string $attrValue[] = stringToStringArray($allAttr[$j], " ");
                string $attrName = substituteAllString($attrValue[0], ".", "");
                if(`attributeExists $attrName $ctrl[$i]`){
                    string $connections[] = `listConnections -d off -s on ($ctrl[$i]+$attrValue[0])`;
                    if(`getAttr -k ($ctrl[$i]+$attrValue[0])` && !size($connections) && !`getAttr -l ($ctrl[$i]+$attrValue[0])`){
                        float $value = $attrValue[1];
                        setAttr ($ctrl[$i]+$attrValue[0]) $value;
                    }
                }
            }
        }
    }
    else{
        bbstg_bb_QC_noneQC;
    }
}

//------------------------------选面贴------------------------------//
global proc bbstg_bb_QC_faceMappingQC()
{
    if(`objExists "QC_faceMappingSets"`) delete "QC_faceMappingSets";
    string $allMesh[] = `ls -type "mesh"`;
    string $setObj[];
    for($i=0;$i<size($allMesh);$i++){
        string $shaderSG[] = `listConnections -t "shadingEngine" $allMesh[$i]`;
        $shaderSG = stringArrayRemoveDuplicates($shaderSG);
        if(size($shaderSG) > 1){
            $setObj[size($setObj)] = $allMesh[$i];
        }
    }
    bbstg_bb_QC_setApply($setObj,"QC_faceMappingSets",14);
}

//------------------------------动画帧------------------------------//
global proc bbstg_bb_QC_animKeyQC()
{
    if(`objExists "QC_animKeySets"`) delete "QC_animKeySets";
    string $animCurveTL[] = `ls -type "animCurveTL"`;
    string $animCurveTA[] = `ls -type "animCurveTA"`;
    string $animCurveTU[] = `ls -type "animCurveTU"`;
    string $animCurveNode[] = stringArrayCatenate($animCurveTL, $animCurveTA);
    $animCurveNode = stringArrayCatenate($animCurveNode, $animCurveTU);
    string $setObj[];
    for($i=0;$i<size($animCurveNode);$i++){
        string $animObj[] = `listConnections -d on -s off $animCurveNode[$i]`;
        if(size($animObj)){
            $setObj[size($setObj)] = $animObj[0];
        }
    }
    $setObj = stringArrayRemoveDuplicates($setObj);
    bbstg_bb_QC_setApply($setObj,"QC_animKeySets",15);
}

global proc bbstg_bb_QC_animKeyFix()
{
    if(`objExists "QC_animKeySets"`){
        string $animCurveTL[] = `ls -type "animCurveTL"`;
        string $animCurveTA[] = `ls -type "animCurveTA"`;
        string $animCurveTU[] = `ls -type "animCurveTU"`;
        string $animCurveNode[] = stringArrayCatenate($animCurveTL, $animCurveTA);
        $animCurveNode = stringArrayCatenate($animCurveNode, $animCurveTU);
        for($i=0;$i<size($animCurveNode);$i++){
            if(`objExists $animCurveNode[$i]`)
                delete $animCurveNode[$i];
        }
    }
    else{
        bbstg_bb_QC_noneQC;
    }
}
//------------------------------显示层------------------------------//
global proc bbstg_bb_QC_layerQC()
{
    if(`objExists "QC_layerSets"`) delete "QC_layerSets";
    string $layerNode[] = `ls -type "displayLayer"`;
    $layerNode = stringArrayRemove({"defaultLayer"}, $layerNode);
    bbstg_bb_QC_setApply($layerNode,"QC_layerSets",16);
}
//------------------------------smooth------------------------------//
global proc bbstg_bb_QC_smoothQC()
{
    int $connect = `checkBox -q -v bb_QC_smoothConCB`;
    if(`objExists "QC_smoothPositionSets"`) delete "QC_smoothPositionSets";
    if(`objExists "QC_smoothAddSets"`) delete "QC_smoothAddSets";
    if(`objExists "QC_smoothConnectSets"`) delete "QC_smoothConnectSets";
    string $smoothObj[] = bbstg_bb_QC_suffixQCApply("bb_QC_smoothSuffixTF","mesh",1);
    string $allObj[] = bbstg_bb_QC_shapes2transforms("mesh");
    string $falsePosition[],$falseAdd[],$falseConnect[];
    for($i=0;$i<size($allObj);$i++){
        string $history[] = `listHistory -groupLevels 1 -pruneDagObjects 1 $allObj[$i]`;
        int $smoothExists = 0;
        for($j=0;$j<size($history);$j++){
            if(`nodeType $history[$j]` == "polySmoothFace"){
                if(stringArrayContains($allObj[$i], $smoothObj)){
                    $smoothExists += 1;
                    if($j > 0){
                        $falsePosition[size($falsePosition)] = $allObj[$i];
                    }
                    string $connect[] = `listConnections -d off -s on ($history[$j]+".divisions")`;
                    if(!size($connect)){
                        $falseConnect[size($falseConnect)] = $allObj[$i];
                    }
                }
                else{
                    $falseAdd[size($falseAdd)] = $allObj[$i];
                }
            }
        }
        if($smoothExists != 1 && stringArrayContains($allObj[$i], $smoothObj)){
            $falseAdd[size($falseAdd)] = $allObj[$i];
        }
    }
    $falseAdd = stringArrayRemoveDuplicates($falseAdd);
    $falsePosition = stringArrayRemoveDuplicates($falsePosition);
    bbstg_bb_QC_setApply($falseAdd,"QC_smoothAddSets",17);
    bbstg_bb_QC_setApply($falsePosition,"QC_smoothPositionSets",18);
    if($connect == 1){
        $falseConnect = stringArrayRemoveDuplicates($falseConnect);
        bbstg_bb_QC_setApply($falseConnect,"QC_smoothConnectSets",19);
    }
}

global proc bbstg_bb_QC_smoothFix()
{
    if(`objExists "QC_smoothAddSets"`){
        string $setObj[] = `sets -q "QC_smoothAddSets"`;
        string $smoothObj[] = bbstg_bb_QC_suffixQCApply("bb_QC_smoothSuffixTF","mesh",1);
        for($i=0;$i<size($setObj);$i++){
            string $longName[] = `ls -l $setObj[$i]`;
            int $mode = stringArrayContains($longName[0], $smoothObj);
            bbstg_bb_QC_smoothFixAddApply($setObj[$i],$mode);
        }
    }
    if(`objExists "QC_smoothPositionSets"`){
        string $setObj[] = `sets -q "QC_smoothAddSets"`;
        for($i=0;$i<size($setObj);$i++){
            string $history[] = `listHistory -groupLevels 1 -pruneDagObjects 1 $setObj[$i]`;
            for($j=0;$j<size($history);$j++){
                if(`nodeType $history[$i]` == "polySmoothFace") delete $history[$i];
            }
            polySmooth -mth 0 -sdt 2 -ovb 1 -ofb 3 -ofc 0 -ost 1 -ocr 0 -dv 0 -bnr 1 -c 1 -kb 1 -ksb 1
                       -khe 0 -kt 1 -kmb 1 -suv 1 -peh 0 -sl 1 -dpe 1 -ps 0.1 -ro 1 -ch 1 $setObj[$i];
        }
    }
}

global proc bbstg_bb_QC_smoothFixAddApply(string $obj,int $mode)
{
    string $history[] = `listHistory -groupLevels 1 -pruneDagObjects 1 $obj`;
    string $smoothNode[];
    for($i=0;$i<size($history);$i++){
        if(`nodeType $history[$i]` == "polySmoothFace"){
            if($mode == 0) delete $history[$i];
            if($mode == 1) $smoothNode[size($smoothNode)] = $history[$i];
        }
    }
    if(size($smoothNode) == 0 && $mode == 1){
        polySmooth -mth 0 -sdt 2 -ovb 1 -ofb 3 -ofc 0 -ost 1 -ocr 0 -dv 0 -bnr 1 -c 1 -kb 1 -ksb 1
                   -khe 0 -kt 1 -kmb 1 -suv 1 -peh 0 -sl 1 -dpe 1 -ps 0.1 -ro 1 -ch 1 $obj;
    }
    else if(size($smoothNode) > 1 && $mode == 1){
        for($i=1;$i<size($smoothNode);$i++){
            delete $smoothNode[$i];
        }
    }
}
//------------------------------无影响骨骼------------------------------//
global proc bbstg_bb_QC_unusedQC()
{
    if(`objExists "QC_unusedSets"`) delete "QC_unusedSets";
    string $setObj[];
    string $skinNode[] = `ls -type "skinCluster"`;
    for($i=0;$i<size($skinNode);$i++){
        string $infls[] = `skinCluster -q -inf $skinNode[$i]`;
        string $wtinfs[] = `skinCluster -q -wi $skinNode[$i]`;
        if(size($infls) != size($wtinfs)){
            string $skinClusterSet[] = `listConnections -d 1 -s 0 ($skinNode[$i]+".message")`;
            string $modle[] = `listConnections -d 1 -s 0 $skinClusterSet[0]`;
            if(size($modle)){
                $setObj[size($setObj)] = $modle[0];
            }
        }
    }
    bbstg_bb_QC_setApply($setObj,"QC_unusedSets",20);
}

global proc bbstg_bb_QC_unusedFix()
{
    if(`objExists "QC_unusedSets"`){
        string $obj[] = `sets -q "QC_unusedSets"`;
        select -r $obj;
        removeUnusedInfluences;
        select -cl;
    }
    else{
        bbstg_bb_QC_noneQC;
    }
}
