/* dofControl.mel V1.0

This script may be freely distributed. Modify at your own risk.

Author: Dirk Bialluch <DirkBi@Software2000.de> <http://dirk-bialluch.mayaring.com>

Creation date:	12.01.2000
Last update:	13.01.2000

Description
	This script creates a DOF control (polyCube) for selected cameras.

	TranslateZ = focus distance
	ScaleZ = focus range

NOTE
	The polyCube will not appear in the rendered image. To hide the cube
	in shaded view use 'toggle template'.
*/

//
// Main
//

global proc string[] mtbDOF_build (string $objList[], string $prefix)
{
	python("from maya_toolkit.tools.dof_control_v1_0.runtime import require_active; require_active()");
    string $result[];
	print $objList;

	if ( !size( $objList ) )
	{
		print "No camera node(s) selected\n";
		return $result;
	}

	// iterate through list of camera shapes
	for ( $objCnt = 0; $objCnt < size( $objList ); $objCnt++ )
	{
		// get cameraShape transform node
		string $camTransNode[] = `listRelatives -parent $objList[$objCnt]`;
		print $camTransNode[0];

		// get current settings from camera
		float $oldFocusDistance = `getAttr ( $objList[$objCnt] + ".focusDistance" )`;
		float $oldFStop = `getAttr ( $objList[$objCnt] + ".fStop" )`;

		// create polyCube for DOF area display
		string $cube[] = `polyCube -sx 1 -sy 1 -sz 1 -ch off`;
		$cube[0] = `rename $cube[0] ( $prefix + "Area#" )`;
		setAttr -lock true ( $cube[0] + ".tx" );
		setAttr -lock true ( $cube[0] + ".ty" );
		setAttr -lock true ( $cube[0] + ".rx" );
		setAttr -lock true ( $cube[0] + ".ry" );
		setAttr -lock true ( $cube[0] + ".rz" );
		setAttr ( $cube[0] + ".tz" ) ( -$oldFocusDistance );
		setAttr ( $cube[0] + ".sz" ) $oldFStop;
		string $cubeShape[] = `listRelatives -shapes -fullPath $cube[0]`;
		setAttr ( $cubeShape[0] + ".castsShadows" ) 0;
		setAttr ( $cubeShape[0] + ".primaryVisibility" ) 0;
		setAttr ( $cubeShape[0] + ".visibleInReflections" ) 0;
		setAttr ( $cubeShape[0] + ".visibleInRefractions" ) 0;

		// parent polyCube to camera
		parent -r $cube[0] $camTransNode[0];

		// create 'reverse' node
		string $revNode = `createNode -name ($prefix + "Reverse#") "reverse"`;

		// create 'add' node
		string $addNode = `createNode -name ($prefix + "Add#") "addDoubleLinear"`;
		setAttr ( $addNode + ".input2" ) 1;

		// make connections
		connectAttr ( $cube[0] + ".translateZ" ) ( $addNode + ".input1" );
		connectAttr ( $addNode + ".output" ) ( $revNode + ".inputX" );
		connectAttr ( $revNode + ".outputX" ) ( $objList[$objCnt] + ".focusDistance" );

		connectAttr ( $cube[0] + ".scaleZ" ) ( $objList[$objCnt] + ".fStop" );

		connectAttr ( $cube[0] + ".tz" ) ( $cube[0] + ".sx" );
		connectAttr ( $cube[0] + ".tz" ) ( $cube[0] + ".sy" );
		$result[size($result)] = $cube[0];
		$result[size($result)] = $revNode;
		$result[size($result)] = $addNode;
	}
    return $result;
}

// end of script
