// bh_speedLines v1.02 19-11-2020 



// added depth slider for the drawing plane
// added about menu
// now the smooth curve and simplify curve procs do a center pivot on the curve(s) too 
// make geo proc now freezes rotation on the geo relative to the camera so that it can be moved easily in camera space.. 
// fixed key vis so it doesn't key the shape node too
// put in ScriptJob to toggle the Draw mode off if the user hits Enter or switches tool while drawing IN EP MODE ONLY

// added option to use EP tool instead of Pencil 
// add the 'simplify curve proc'
// simplify geo now works with multiple selected meshes
// various UI tweaks
// made camera field non-editable so that it doesn't steal focus (makes Undoing more fluid when using tools)
// made the 'flip' command work with multiple meshes
// set up good default settings for geometry creation
// added option to create high-res geo
// improved Draw button so that it's a toggle rather than 2 separate buttons, also changes color to make it clear when in drawing mode
// added option to key visibility for 2 frames 
// added an option to set up a display layer for geo and have new drawn geo added to it on create
// took out the simplify geo happening by default when converting..




global proc bh_speedLines()
{
    bh_setUpConvertPrefs;
    bh_speedLinesUI;
}


bh_speedLines;

global proc bh_setUpConvertPrefs()
{// set this to get Quad meshes from conversion.. // these settings should give good results in the majority of cases.. 
    	
nurbsToPolygonsPref  -f 0 -pt 1 -pc 100 -chr 0.1 -ft 0.01 -mel 0.001 -d 0.1 -ut 1 -un 3 -vt 1 -vn 3 -uch 0 -ucr 0 -cht 0.2 -es 0  -mrt 0  ;
    	 
}


global proc bh_speedLinesUI()
{

string $version = "1.02 Nov 19 2020";

if (`window -exists bh_speedLinesUI`)
        deleteUI bh_speedLinesUI;
		
		window -toolbox 1 -width 200 -t "bh_speedLinesUI" -mxb 0 -mnb 0 -menuBar 1 bh_speedLinesUI;
       
//		menu -l "Options" -to 1 bhSpeedLinesOptionsMenu;
		menu -l "选项" -to 1 bhSpeedLinesOptionsMenu;
//		menuItem -l "Hold Visibility for 2 frames when Keying" -cb 0  bhsl_vis2s;
		menuItem -l "设置关键帧时保持2帧可见性" -cb 0  bhsl_vis2s;
//		menuItem -l "Put Drawn Geo on a Display Layer" -cb 0  bhsl_layerSwitch;
		menuItem -l "将绘制的Geo放置在显示层上" -cb 0  bhsl_layerSwitch;
//		menuItem -l "Create High Detail Geometry" -cb 0  bhsl_detailSwitch;
		menuItem -l "C创建高细节几何图形" -cb 0  bhsl_detailSwitch;
//		menuItem -l "Use EP curve tool when Drawing (more mouse-friendly) " -cb 0  bhsl_toolMode;
		menuItem -l "绘制时使用EP曲线工具（更方便鼠标） " -cb 0  bhsl_toolMode;
//		menu -l "  About" -to 1 bhslaboutMenu5;
		menu -l "  关于" -to 1 bhslaboutMenu5;
		menuItem -l $version   -c goToG9Site aboutlabe500;
		
		
		
		 columnLayout -adj 1 -rowSpacing 0 -columnWidth 10 MainTools;
		
		floatField -vis false -v 0 bhSL_depthField;// creating an invisible float field to store the depth in

					floatSliderGrp 	//-label "DrawDepth" 
									-field 0
									-minValue -50 -maxValue 50
									
									-value 0
									-step 0.001
									-cw2 1 100
									-cat 1 "left" 0
									-cat 2 "left" 0
							        -dc "bhSL_drawDepth();"
							        -cc "bhSL_drawDepthReset();"
							        //-parent ROW_bh_camZoom_03
							        "bhSL_drawDepthSlider";
			 //separator -w 20 -style "in";
			  rowColumnLayout -numberOfColumns 2
			  -columnWidth 1 100;
        
        setParent ..;
       
        
        	 rowColumnLayout -numberOfColumns 2
			 -columnWidth 1 100
		  -columnWidth 2 100;
        
//        button -label "Choose Camera >" -ann " Choose the Camera to draw in " -backgroundColor .3 .3 .3 -command "bh_camList_SL_UI" but2;
        button -label "选择相机>" -ann " 选择要绘制速度线的相机 " -backgroundColor .3 .3 .3 -command "bh_camList_SL_UI" but2;
        textField  -editable false -backgroundColor .1 .1 .1  -text "persp" bh_SL_cameraField;  // PUTTING IN PERSP BY DEFAULT FOR SPEED OF TESTING.. 
				   
					  setParent ..;
				
					  rowColumnLayout -numberOfColumns 1;
			  separator -h 5 -style "in";	
			  	  setParent ..;
				
					  rowColumnLayout -numberOfColumns 2
			  -columnWidth 1 100
			  -columnWidth 2 100;
        
        
		
		
//		button -label "Make Geometry" -ann "Select any TWO curves and run to create geometry from them" -command bh_geoFrom2Curves but6;
		button -label "生成几何体" -ann "选择任意两条曲线并运行以从中创建几何体" -command bh_geoFrom2Curves but6;
		
		//button -label "Exit Draw Mode" -command "bh_exitDraw" but4;
		button -label "法线反转" -ann "翻转选定网格的法线 " -command bh_reverseNormals but7;

//		button -label "Simplify" -ann "This will reduce the detail of selected Geometry OR Curve objects.." -command bh_simplify but8;
		button -label "简化" -ann "这将减少选定几何体或曲线对象的细节.." -command bh_simplify but8;
		
		//button -label "" -command bhDummy "bhTestButton";
		
//		button -label "Key Vis" -ann "Keyframes the visibility of the selected mesh(es) to be on on current frame and off on previous/next frames - see options to set this to 2 frames" -command bh_keyVisibility but9;
		button -label "设置可视化关键帧" -ann "为选定网格的可见性设置关键帧，使其在当前帧打开，在上一帧/下一帧关闭-请参见将其设置为2帧的选项" -command bh_keyVisibility but9;
		
        
		
		
		setParent ..;
		separator -h 5 -style "in";
//		button -label "Smooth Curve" -bgc .5 .7 .7 -command bh_smoothCurves but5;
		button -label "平滑曲线" -bgc .5 .7 .7 -command bh_smoothCurves but5;
		separator -h 5 -style "in";
//		button -label "Enter Drawing Mode" -bgc .2 .2 .2 -command bh_toggleDrawMode "bh_toggleDrawMode";
		button -label "进入绘图模式" -bgc .2 .2 .2 -command bh_toggleDrawMode "bh_toggleDrawMode";
		separator -h 5 -style "in";
		

			//intField  -editable false -backgroundColor .1 .1 .1   bh_SL_scriptNumField;	
showWindow bh_speedLinesUI;
}



// procs to change the depth of the draw field.. 

global proc bhSL_drawDepth()
{
// show the draw plane
	if (`objExists "SL_Draw_Plane"`)
	{
	   setAttr ("SL_Draw_Plane.visibility") 1; 
	   
	   float $depthOffsetVal=`floatField -q -v  bhSL_depthField`;
	   float $sliderVal=`floatSliderGrp -q -v  bhSL_drawDepthSlider`;
	   
	   float $newDepth=($depthOffsetVal+$sliderVal);
	   
	   // need to make sure the draw plane doesn't come nearer than the clipping plane..
	   string $cameraToUse =`textField -q -text bh_SL_cameraField`;
		string $camShap[] =`listRelatives -s $cameraToUse`;

		float $nearClipPlaneVal=`getAttr ($camShap[0]+".nearClipPlane")`*-1;
	   if ($newDepth>$nearClipPlaneVal) $newDepth=($nearClipPlaneVal*1.01);
	 
	   setAttr ("SL_Draw_Plane.tz") $newDepth;
	}
	
	
	}

global proc bhSL_drawDepthReset()
{
// reset the slider..



// hide the draw plane 
if (`objExists "SL_Draw_Plane"`)
	{
	   setAttr ("SL_Draw_Plane.visibility") 0; 
	   
	   string $cameraToUse =`textField -q -text bh_SL_cameraField`;
	   
	   // store the offset in the insible float field
	float $longCurDepth =`getAttr ("SL_Draw_Plane.tz")`;
	float $curDepth= bhSLcutDecimals ($longCurDepth);
	floatField -e -v $curDepth bhSL_depthField;
	   
	print ("绘图平面深度设置为 "+$curDepth);   
	}
floatSliderGrp -e -v 0 "bhSL_drawDepthSlider";
}


global proc float bhSLcutDecimals(float $number)
  {
  return (float(int($number*100))/100);
  }






global proc bh_toggleDrawMode()
{
    string $curMode =`button -q -label "bh_toggleDrawMode"`;
    if ($curMode=="进入绘图模式")
    {
        button -e -label "退出绘图模式"-bgc .7 .7 .7  "bh_toggleDrawMode";
        bh_drawPlane;
		
    }
     if ($curMode=="退出绘图模式")
    {
        button -e -label "进入绘图模式" -bgc .2 .2 .2 "bh_toggleDrawMode";
        bh_exitDraw;
	
    }
    
    
}


/////////////////////////////////////////////////////////////////////////



// SELECT CAMERA PROCS.. 


// add list of scene cameras to text scroll list
global proc bhUpdateWin (){
    string    $cams[] = `listCameras`;                //create an array of all the cameras in the scene
   
    
    textScrollList -e -ra "bhScrollList";            //clear the scroll list before adding new stuff
                                                    
    //the list is now empty
    for ($each in $cams)
    {                       
     
       
       
         string $foundShapeNode=`match "Shape" $each`; // sometimes the shape node for a shot cam is found.. 
        if ($foundShapeNode=="")
        {
        textScrollList    -edit      -append    $each    "bhScrollList"; 
        }   
        if ($foundShapeNode=="Shape")
        {
        string $camTransform[] = `listRelatives  -p $each`; 
        textScrollList    -edit      -append    $camTransform[0]    "bhScrollList"; 
        }                 
    }
}

// proc for updating the hidden text field with the correct name of the camera based on animator selection
global proc bh_scrollWinUpdateSel (){
    string    $cameraSel[] = `textScrollList                 
            -query                                
            -selectItem                            
            "bhScrollList"`;                        
   

   
   textField -e -text $cameraSel[0] bh_SL_cameraField;


   deleteUI "bh_camList_SL_UI";     
}


global proc bh_camList_SL_UI (){

    if (`window -ex "bh_camList_SL_UI"`)                    //does the window already exist?
        deleteUI "bh_camList_SL_UI";                        //if it does, kill it
    
    //define the window
    window                                         //create a window
//        -title "Camera List"                 //give it a title
        -title "摄像机列表"                 //give it a title
		-toolbox 1 
		-rtf true 
		-menuBar 1
        -w 150 -h 200  
	//set width and height
		//-cc	bhCloseCamSelectWin
        "bh_camList_SL_UI";                                //give the window a unique name
        columnLayout -w 150;                        //create a column
            
            text -l "" -h 10;  
//            text "  Please Select Camera  ";
            text "  请选择摄像机  "; 
            text -l "" -h 10;   
                            //text spacer
            textScrollList                        //set up the scroll list
                -h 200
                -w 250
                -ams false                        //disallow multiple selections
                -sc "bh_scrollWinUpdateSel"            //the command used when an item is selected
                "bhScrollList";                    //the control is given a unique, explicit name
            //textField -w 240 "scTextField";        //text field also gets a unique name
            //text -l "" -h 10;                    //text spacer
            
    bhUpdateWin;                                    //call a general purpose window update
            
    showWindow "bh_camList_SL_UI";                        //tell Maya to draw the window
}

////////////////////////////////////////////////////////


global proc bh_drawPlane()
{
string $cameraToUse =`textField -q -text bh_SL_cameraField`;
    if ($cameraToUse=="")
    {error "请先选择相机！";
    }
    
    if (!`objExists $cameraToUse`)
    {
        error ("相机  "+$cameraToUse+" 不存在，请先使用“选择相机”按钮！");
    }
    
    
if (`objExists "SL_Draw_Plane"`)
{
   delete "SL_Draw_Plane"; 
}
string $drawPlane=`plane -n "SL_Draw_Plane"`;


parent  $drawPlane $cameraToUse;
// zero out the rotation of the plane
setAttr ($drawPlane+".rx") 0;

setAttr ($drawPlane+".ry") 0;
setAttr ($drawPlane+".rz") 0;
//reset x and y coords
setAttr ($drawPlane+".tx") 0;
setAttr ($drawPlane+".ty") 0;

setAttr ($drawPlane+".visibility") 0;

float $depthOffsetVal=`floatField -q -v  bhSL_depthField`;

if ($depthOffsetVal!=0)
{setAttr ($drawPlane+".tz") $depthOffsetVal;
}

makeLive $drawPlane;

int $altToolMode= `menuItem -query -cb  bhsl_toolMode`;

	if ($altToolMode==1)
		{
		EPCurveTool;
		print "绘图模式已启用-使用EP工具而不是铅笔";
		
		// putting in an experimental option here to track took changes  toggles off if the user exits the tool or hits enter
		int $scriptNum=`scriptJob -runOnce true -event "ToolChanged" bh_exitEPDrawMode`;
		// store the scriptJob int in a hidden field in the GUI so we can delete it later.. 
		//intField -e -v $scriptNum bh_SL_scriptNumField;
		
		}
	else {
		PencilCurveTool;
		print "绘图模式已启用";
		

		}

}


global proc bh_exitDraw()
{
	if (`objExists "SL_Draw_Plane"`)
	{
	   delete "SL_Draw_Plane"; 
	}


setToolTo moveSuperContext;
print "绘图模式已退出";
}


global proc bh_exitEPDrawMode()
{
	if (`objExists "SL_Draw_Plane"`)
	{
	   delete "SL_Draw_Plane"; 
	}


button -e -label "Enter Drawing Mode" -bgc .2 .2 .2 "bh_toggleDrawMode";

print "绘图模式已退出";
}





global proc bh_smoothCurves(){
    
 SmoothHairCurves;
 
 string $sel[]=`ls -sl`;
 for ($each in $sel)
 {
 select -r $each;
    CenterPivot;
 }
 select -r $sel;
 
}

global proc bh_geoFrom2Curves()
{

	
    string $sel[]=`ls -sl`;
    if (`size $sel`!=2)
    {
        error "请选择2条曲线";
        
    }
    
    // check is the 'high detail geometry option enabled 
       int $highRes= `menuItem -query -cb  bhsl_detailSwitch`;
       if ($highRes==1)
           {
               nurbsToPolygonsPref   -pc 500;
           }
       else {
           nurbsToPolygonsPref   -pc 100;
       }
    
    string $newLoftGeo[]=`loft -ch 0 -polygon 1 -ar 1 -c 0 -rsn false -name "DrawnGeo"`;
    select -r $newLoftGeo;
    CenterPivot;
    displaySmoothness -divisionsU 3 -divisionsV 3 -pointsWire 16 -pointsShaded 4 -polygonObject 3;
    
    
    // check here should the new geo go on a display layer ? 
    int $onLayer= `menuItem -query -cb  bhsl_layerSwitch`;
    if ($onLayer==1)
    {
    //string $origSel[]=`ls -sl`;
        // does the layer exist ??
        if (!`objExists ("bh_DrawnGeoL")`)
    	{   	
    	//select -cl;
    	string $drawnGeoLayer= `createDisplayLayer -name "bh_DrawnGeoL"`;
        }    
        
    //select -r $origSel;
    editDisplayLayerMembers -noRecurse "bh_DrawnGeoL" `ls -selection`; 
	
	
	   
    }
       // parent the geo temporarily to the camera to freeze its rotation..
	string $cameraToUse =`textField -q -text bh_SL_cameraField`;

    if (`objExists $cameraToUse`)
    {
       parent $newLoftGeo[0] $cameraToUse;
	   //freeze rotation channels
	   makeIdentity -apply true  -r 1 ;
	   parent -w $newLoftGeo[0] ;     
         
    }
    
    //bh_simplify;
    delete $sel;
    
    print "已成功创建绘图几何图形";
}

global proc bh_reverseNormals()
{
    string $sel[]=`ls -sl`;
    for ($eachMesh in $sel)
    { select -r $eachMesh;
    polyNormal -normalMode 0 -userNormalMode 0 -ch 0;
    print ("翻转 "+$eachMesh+"的法线");
    }
    select -r $sel;
}


global proc bh_simplify()
{
    string $sel[]=`ls -sl`;
    for ($each in $sel)
    {
        string $shape[] =`listRelatives -s $each`;
        string $nodeType =`nodeType $shape`;
        
        if ($nodeType=="mesh")
            {   select -r $each;
                bh_simplifyGEO;
            }
         if ($nodeType=="nurbsCurve")
            {   select -r $each;    
				CenterPivot;
                bh_simplifyCurve;
            }
     
     select -r $sel;// restore original selection
        
    }

}
global proc bh_simplifyGEO()
    {
        string $sel[]=`ls -sl`;
       
        polyReduce  -ver 1 -trm 0 -shp 0 -keepBorder 1 -keepMapBorder 1 -keepColorBorder 1 -keepFaceGroupBorder 1 -keepHardEdge 1 -keepCreaseEdge 1 -keepBorderWeight 0.5 -keepMapBorderWeight 0.5 -keepColorBorderWeight 0.5 -keepFaceGroupBorderWeight 0.5 -keepHardEdgeWeight 0.5 -keepCreaseEdgeWeight 0.5   -sx 0 -sy 1 -sz 0 -sw 0 -preserveTopology 1 -keepQuadsWeight 1  -cachingReduce 1 -ch 0 -p 50 -vct 0 -tct 0 -replaceOriginal 1 ;
        print ("简化几何： " +$sel[0]);
    }

global proc bh_keyVisibility()
{
    string $sel[]=`ls -sl`;
    int $currentTime =`currentTime -q`;
    
    int $on2S= `menuItem -query -cb  bhsl_vis2s`;
	
    for ($each in $sel)
    {
    setKeyframe  -s 0 -v 1 -at "visibility"  -time $currentTime $each; // NB! using the -shapes flag to make sure shape vis is NOT keyed
    setKeyframe  -s 0 -v 0 -at "visibility"  -time ($currentTime-1) $each;
    setKeyframe  -s 0 -v $on2S -at "visibility"  -time ($currentTime+1) $each;
    
        if ($on2S==1)// key the visibility on 2s so add one more key set to off 2 frames from current time..
        {
            setKeyframe  -s 0 -v 0 -at "visibility"  -time ($currentTime+2) $each;
        }
    }
    
    
    
}



global proc bh_simplifyCurve()
{
    string $thisCurve[]=`ls -sl`;
	
	
	
    string $thisCurveShape[] =`listRelatives -s $thisCurve[0]`;
    //print $thisCurveShape;
    int $cvs=`getAttr ($thisCurveShape[0]+".spans")`;
    int $newcvCount=$cvs/2; // half the CV count - will round down due to discarding decimal place..
    // now rebuild the curve 

   rebuildCurve -ch 0 -rpo 1 -rt 0 -end 1 -kr 0 -kcp 0 -kep 1 -kt 0 -s $newcvCount -d 2 -tol 0.0001 $thisCurve[0];
   print ("简化曲线 : " +$thisCurve[0]);
}

 global proc goToG9Site ()
	    {
	        launch -web "https://www.bilibili.com/list/656262?sid=3024991&spm_id_from=333.999.0.0&desc=1&oid=351582034&bvid=BV1rR4y1q7Bo";
	    };
