from __future__ import absolute_import, division, print_function, unicode_literals

ICON_KEYWORD_RULES = [
    ("toggle nurbs cv", "controller"),
    ("toggle nurbs hull", "curve"),
    ("toggle nurbs curve", "curve"),
    ("toggle nurbs surface", "sphere"),
    ("toggle subdivision", "cube"),
    ("toggle polygon", "cube"),
    ("toggle joint", "joint"),
    ("toggle ik handle", "ik_handle"),
    ("toggle manipulator", "move"),
    ("toggle locator", "target"),
    ("toggle light", "light"),
    ("toggle camera", "camera"),
    ("toggle grid", "layers"),
    ("toggle hud", "flag"),
    ("toggle wireframe", "mesh"),
    ("toggle xray", "eye"),
    ("toggle motion trail", "motion_path"),
    ("toggle particle instancer", "sparkle"),
    ("toggle nparticle", "sparkle"),
    ("toggle ncloth", "wave"),
    ("toggle nrigid", "cube"),
    ("toggle fluid", "wave"),
    ("toggle hair system", "curve_warp"),
    ("toggle follicle", "curve_warp"),
    ("toggle dynamic constraint", "constraint"),
    ("toggle dynamics", "lightning"),
    ("toggle deformer", "wrap_deformer"),
    ("toggle plugin shape", "diamond_control"),
    ("toggle strokes", "brush"),
    ("toggle texture placement", "gradient"),
    ("toggle gpu cache", "layers"),
    ("toggle pivot", "pin"),
    ("toggle handle", "controller"),
    ("toggle imageplane", "camera"),
    ("toggle image plane", "camera"),
    ("toggle construction plane", "square_control"),
    ("toggle dimension", "crosshair"),
    ("toggle isolate", "eye"),
    ("toggle selection highlighting", "select"),
    ("toggle blue pencil", "pen"),
    ("toggle clip ghost", "eye_closed"),
    ("toggle controls display", "controller"),
    ("toggle controller", "controller"),
    ("toggle geometry", "cube"),
    ("toggle", "eye"),
    ("ik handle", "ik_handle"),
    ("fk chain", "fk_chain"),
    ("xform relationship", "link"),
    ("xform range", "transform"),
    ("xform", "transform"),
    ("attribute space switcher", "link"),
    ("pickify", "select_multiple"),
    ("spacify", "link"),
    ("twosify", "layers"),
    ("transify", "link"),
    ("tweenify", "slider"),
    ("select opposite", "select_multiple"),
    ("select hierachy", "select_multiple"),
    ("select hierarchy", "select_multiple"),
    ("select objects from keys", "keyframe"),
    ("select objects in anim layer", "layers"),
    ("select", "select"),
    ("mirror pose", "flip_horizontal"),
    ("mirror", "flip_horizontal"),
    ("blend to default", "blend"),
    ("blend to neighbors", "blend"),
    ("blend to world", "blend"),
    ("blend", "blend"),
    ("cascade", "layers"),
    ("ease", "wave"),
    ("tween", "slider"),
    ("auto tangent", "curve"),
    ("linear tangent", "curve"),
    ("step tangent", "curve"),
    ("tangent", "curve"),
    ("noise", "sparkle"),
    ("wave", "wave"),
    ("push", "arrows_expand"),
    ("pull", "arrows_compress"),
    ("scale", "scale"),
    ("rotate order", "rotate"),
    ("rotate", "rotate"),
    ("time offset stagger", "skip_forward"),
    ("time offset", "timeline"),
    ("offset sequentially left", "skip_backward"),
    ("offset sequentially right", "skip_forward"),
    ("nudge left", "arrow_left"),
    ("nudge right", "arrow_right"),
    ("nudge", "arrow_left"),
    ("fast bake", "record"),
    ("bake", "record"),
    ("keyframe reducer", "keyframe"),
    ("key timing", "keyframe"),
    ("clean keys", "keyframe"),
    ("smart snap keys", "magic_wand"),
    ("smooth selected keys", "smooth_weights"),
    ("keys", "keyframe"),
    ("keyframe", "keyframe"),
    ("graph editor", "graph"),
    ("channel box", "layers"),
    ("clear channel box selection", "eraser"),
    ("copy selected channels", "copy_weights"),
    ("smart copy", "copy_weights"),
    ("smart paste", "paint_weights"),
    ("copy", "copy_weights"),
    ("paste", "paint_weights"),
    ("animation visibility", "eye"),
    ("clear animation", "eraser"),
    ("crop animation", "lasso"),
    ("reverse animation", "flip_horizontal"),
    ("insert animation", "keyframe"),
    ("replace animation", "keyframe"),
    ("add selected to anim layer", "layers"),
    ("update selected layer", "layers"),
    ("snapshot", "camera"),
    ("smart go to next", "skip_forward"),
    ("smart go to previous", "skip_backward"),
    ("pose", "controller"),
    ("foot locker", "foot_rig"),
    ("temp ik", "ik_handle"),
    ("temp pivot", "pin"),
    ("pivot", "pin"),
    ("locator", "target"),
    ("world orient", "orbit"),
    ("world", "sphere"),
    ("group", "group"),
    ("align", "position"),
    ("axis orientation", "orbit"),
    ("automatically hide static channels", "eye_closed"),
    ("change selected locators color", "palette"),
    ("delete redundant keys", "eraser"),
    ("share keys", "link"),
    ("sliders pop up", "slider"),
    ("micro manip", "move"),
    ("new pivot", "pin"),
    ("reset", "eraser"),
    ("relative", "link"),
    ("open nudge keys ui", "wrench"),
    ("open twosify ui", "wrench")
]

DEFAULT_ICON_POOL = [
    "wrench", "star", "flag", "diamond_control", "sparkle",
    "magic_wand", "bookmark", "dial", "controller", "curve"
]

COLOR_KEYWORD_RULES = [
    ("toggle", "#6A8A8A"),
    ("ik handle", "#9A7A5A"),
    ("fk chain", "#9A7A5A"),
    ("foot locker", "#9A7A5A"),
    ("temp ik", "#9A7A5A"),
    ("group", "#9A7A5A"),
    ("xform", "#7A7A9A"),
    ("pivot", "#7A7A9A"),
    ("locator", "#7A7A9A"),
    ("align", "#7A7A9A"),
    ("world", "#7A7A9A"),
    ("axis orientation", "#7A7A9A"),
    ("keys", "#5A9A5A"),
    ("keyframe", "#5A9A5A"),
    ("key timing", "#5A9A5A"),
    ("clean keys", "#5A9A5A"),
    ("smart snap keys", "#5A9A5A"),
    ("smooth selected keys", "#5A9A5A"),
    ("delete redundant keys", "#5A9A5A"),
    ("bake", "#5A9A7A"),
    ("snapshot", "#5A9A7A"),
    ("pose", "#8A6A8A"),
    ("select", "#8A6A8A"),
    ("pickify", "#8A6A8A"),
    ("blend", "#7A6A9A"),
    ("ease", "#7A6A9A"),
    ("tween", "#7A6A9A"),
    ("cascade", "#7A6A9A"),
    ("noise", "#9A5A8A"),
    ("wave", "#9A5A8A"),
    ("push", "#5A8A9A"),
    ("pull", "#5A8A9A"),
    ("scale", "#5A8A9A"),
    ("rotate", "#6A9A7A"),
    ("time offset", "#6A9A7A"),
    ("offset sequentially", "#6A9A7A"),
    ("nudge", "#6A9A7A"),
    ("tangent", "#7A8A7A"),
    ("copy", "#8A7A7A"),
    ("paste", "#8A7A7A"),
    ("animation visibility", "#9A6A6A"),
    ("clear animation", "#9A6A6A"),
    ("crop animation", "#9A6A6A"),
    ("reverse animation", "#9A6A6A"),
    ("insert animation", "#9A6A6A"),
    ("replace animation", "#9A6A6A"),
    ("mirror", "#9A6A6A"),
    ("channel box", "#7A8A8A"),
    ("graph editor", "#7A8A8A"),
    ("attribute space switcher", "#8A8A6A"),
    ("spacify", "#8A8A6A"),
    ("twosify", "#8A8A6A"),
    ("transify", "#8A8A6A"),
    ("tweenify", "#8A8A6A")
]

DEFAULT_COLOR_POOL = [
    "#5A9A5A", "#5A9A7A", "#8A6A8A", "#7A6A9A", "#9A5A8A",
    "#5A8A9A", "#6A8A8A", "#7A7A9A", "#6A9A7A", "#7A8A7A",
    "#8A7A7A", "#9A6A6A", "#7A8A8A", "#9A7A5A", "#8A8A6A"
]

def pick_icon_for_tool(tool_name):
    lowered = tool_name.lower()
    for keyword, icon_name in ICON_KEYWORD_RULES:
        if keyword in lowered:
            return icon_name
    total = 0
    for character in tool_name:
        total += ord(character)
    return DEFAULT_ICON_POOL[total % len(DEFAULT_ICON_POOL)]

def pick_color_for_tool(tool_name):
    lowered = tool_name.lower()
    for keyword, color_hex in COLOR_KEYWORD_RULES:
        if keyword in lowered:
            return color_hex
    total = 0
    for position, character in enumerate(tool_name):
        total += ord(character) * (position + 1)
    return DEFAULT_COLOR_POOL[total % len(DEFAULT_COLOR_POOL)]

def pick_color_for_index(index):
    return DEFAULT_COLOR_POOL[index % len(DEFAULT_COLOR_POOL)]
