# -*- coding: utf-8 -*-
"""Build an Obsidian-readable project catalog without importing Maya tools."""
from __future__ import annotations

import argparse
import ast
import json
import os
import re
import sys
import time
from collections import Counter
from pathlib import Path
from urllib.parse import quote


ROOT = Path(__file__).resolve().parents[1]
KNOWLEDGE = ROOT / "knowledge"
GENERATED = KNOWLEDGE / "_generated"
MARKER = "<!-- Generated by scripts/sync_obsidian_knowledge.py. Edit source files instead. -->"
CODE_SUFFIXES = {".py", ".mel", ".cpp", ".h", ".hpp", ".cs", ".js"}
WATCH_SUFFIXES = CODE_SUFFIXES | {".md", ".json", ".toml"}
IGNORED_DIRS = {"__pycache__", ".git", ".obsidian", "dist", "fbx_sdk_dist", ".knowledge_runtime"}
DOMAIN_NAMES = {
    "animation": "动画与动作",
    "rigging": "角色绑定与变形",
    "modeling_surfacing": "模型与材质",
    "pipeline_io": "资产管线与导入导出",
    "scene_hygiene": "场景健康",
    "engine_bridge": "跨引擎协同",
}
DOC_OVERRIDES = {
    "compare_and_sync_fbx": "docs/tools/fbx_diff_sync_guide.md",
}


def text_file(path):
    return path.read_text(encoding="utf-8-sig", errors="replace")


def parse_python(path):
    try:
        return ast.parse(text_file(path), filename=str(path))
    except (SyntaxError, OSError, UnicodeError):
        return None


def static_value(node):
    try:
        return ast.literal_eval(node)
    except (ValueError, TypeError, SyntaxError, MemoryError):
        if isinstance(node, ast.Attribute) and isinstance(node.value, ast.Name):
            if node.value.id == "ToolDomain":
                return node.attr.lower()
    return None


def class_attributes(node):
    values = {}
    for statement in node.body:
        if isinstance(statement, ast.Assign):
            for target in statement.targets:
                if isinstance(target, ast.Name):
                    values[target.id] = static_value(statement.value)
        elif isinstance(statement, ast.AnnAssign) and isinstance(statement.target, ast.Name):
            values[statement.target.id] = static_value(statement.value)
    return values


def registered_classes():
    tree = parse_python(ROOT / "maya_toolkit" / "tools" / "__init__.py")
    if tree is None:
        return set()
    for node in tree.body:
        if isinstance(node, ast.Assign) and any(
            isinstance(target, ast.Name) and target.id == "ALL_TOOL_CLASSES"
            for target in node.targets
        ):
            if isinstance(node.value, (ast.List, ast.Tuple)):
                return {item.id for item in node.value.elts if isinstance(item, ast.Name)}
    return set()


def package_exports(package):
    tree = parse_python(ROOT / "maya_toolkit" / package / "__init__.py")
    exports = {}
    if tree is not None:
        for node in tree.body:
            if isinstance(node, ast.ImportFrom) and node.level == 1 and node.module:
                for alias in node.names:
                    exports[alias.asname or alias.name] = node.module
    return exports


def code_files(directory):
    files = []
    if not directory.exists():
        return files
    for path in directory.rglob("*"):
        if path.is_file() and path.suffix.lower() in CODE_SUFFIXES:
            if not any(part in IGNORED_DIRS for part in path.relative_to(directory).parts):
                files.append(path)
    return sorted(files)


def code_size(paths):
    return sum(path.stat().st_size for path in paths)


def module_dependencies(files, exports, package):
    result = set()
    for path in files:
        if path.suffix.lower() != ".py":
            continue
        tree = parse_python(path)
        if tree is None:
            continue
        for node in ast.walk(tree):
            if not isinstance(node, ast.ImportFrom):
                continue
            parts = (node.module or "").split(".")
            if package not in parts:
                continue
            index = parts.index(package)
            if index + 1 < len(parts):
                module = parts[index + 1]
                if (ROOT / "maya_toolkit" / package / (module + ".py")).exists():
                    result.add(module)
            else:
                for alias in node.names:
                    module = exports.get(alias.name)
                    if module and (ROOT / "maya_toolkit" / package / (module + ".py")).exists():
                        result.add(module)
    return sorted(result)


def production_tools():
    registered = registered_classes()
    core_exports = package_exports("core")
    framework_exports = package_exports("framework")
    result = []
    base = ROOT / "maya_toolkit" / "tools"
    for tool_path in sorted(base.glob("*/tool.py")):
        tree = parse_python(tool_path)
        if tree is None:
            continue
        for node in tree.body:
            if not isinstance(node, ast.ClassDef):
                continue
            if not any(isinstance(base, ast.Name) and base.id == "BaseMayaTool"
                       or isinstance(base, ast.Attribute) and base.attr == "BaseMayaTool"
                       for base in node.bases):
                continue
            values = class_attributes(node)
            tool_id = values.get("tool_id")
            if not isinstance(tool_id, str) or not tool_id:
                continue
            sources = code_files(tool_path.parent)
            result.append({
                "tool_id": tool_id,
                "name": values.get("tool_name") or tool_id,
                "domain": values.get("category") or "other",
                "version": values.get("version") or "unknown",
                "description": values.get("description") or "",
                "schema": values.get("parameters_schema") or {},
                "class_name": node.name,
                "registered": node.name in registered,
                "source": tool_path,
                "source_files": sources,
                "core_dependencies": module_dependencies(sources, core_exports, "core"),
                "framework_dependencies": module_dependencies(sources, framework_exports, "framework"),
            })
    return sorted(result, key=lambda item: item["tool_id"])


def staging_inventory():
    path = ROOT / "tools_staging_pool" / "README.md"
    items = {}
    if not path.exists():
        return items
    pattern = re.compile(
        r"^\|\s*(\d+)\s*\|\s*([^|]+)\|\s*\*\*(.*?)\*\*\s*\|"
        r"\s*\[[^\]]+\]\((<[^>]+>|[^)]+)\)\s*\|\s*(.*?)\s*\|\s*$"
    )
    for line in text_file(path).splitlines():
        match = pattern.match(line)
        if not match:
            continue
        main_source = match.group(4).strip("<>").replace("\\", "/")
        parts = Path(main_source).parts
        if len(parts) < 2:
            continue
        key = "/".join(parts[:2])
        items[key] = {
            "name": match.group(3).strip(),
            "description": match.group(5).strip(),
            "main_source": main_source,
        }
    return items


def staging_tools():
    inventory = staging_inventory()
    result = []
    base = ROOT / "tools_staging_pool"
    for category in sorted(base.iterdir()):
        if not category.is_dir() or not re.match(r"^\d\d_", category.name):
            continue
        for directory in sorted(category.iterdir()):
            if not directory.is_dir() or directory.name in IGNORED_DIRS:
                continue
            key = category.name + "/" + directory.name
            item = inventory.get(key, {})
            sources = code_files(directory)
            main_source = base / item["main_source"] if item.get("main_source") else None
            if main_source is not None and not main_source.is_file():
                main_source = None
            if main_source is None and sources:
                main_source = sources[0]
            result.append({
                "key": key,
                "slug": category.name + "--" + directory.name,
                "category": category.name,
                "name": item.get("name") or directory.name,
                "description": item.get("description") or "待补充功能说明。",
                "indexed": key in inventory,
                "directory": directory,
                "main_source": main_source,
                "source_files": sources,
            })
    return result, inventory


def module_notes():
    result = []
    for layer in ("core", "framework", "ui"):
        for path in sorted((ROOT / "maya_toolkit" / layer).glob("*.py")):
            if path.name == "__init__.py":
                continue
            tree = parse_python(path)
            symbols = []
            if tree is not None:
                symbols = [
                    node.name for node in tree.body
                    if isinstance(node, (ast.ClassDef, ast.FunctionDef, ast.AsyncFunctionDef))
                    and not node.name.startswith("_")
                ]
            result.append({
                "layer": layer,
                "name": path.stem,
                "path": path,
                "symbols": symbols,
            })
    return result


def verified_workflows(production):
    path = KNOWLEDGE / "relations.json"
    if not path.exists():
        return []
    try:
        payload = json.loads(text_file(path))
    except (ValueError, OSError) as exc:
        raise ValueError("无法读取 knowledge/relations.json: {}".format(exc))
    if not isinstance(payload, dict) or not isinstance(payload.get("verified_workflows"), list):
        raise ValueError("knowledge/relations.json 必须包含 verified_workflows 数组")
    tool_ids = {tool["tool_id"] for tool in production if tool["registered"]}
    result = []
    for item in payload.get("verified_workflows", []):
        if not isinstance(item, dict):
            continue
        source = item.get("from")
        target = item.get("to")
        if source not in tool_ids or target not in tool_ids or source == target:
            continue
        result.append({
            "from": source,
            "to": target,
            "reason": str(item.get("reason", "")),
            "evidence": str(item.get("evidence", "")),
        })
    return result


def yaml_string(value):
    return json.dumps(str(value), ensure_ascii=False)


def header(kind, **properties):
    lines = ["---", "type: " + yaml_string(kind)]
    for key, value in properties.items():
        if isinstance(value, bool):
            lines.append("{}: {}".format(key, str(value).lower()))
        elif isinstance(value, (int, float)):
            lines.append("{}: {}".format(key, value))
        else:
            lines.append("{}: {}".format(key, yaml_string(value)))
    lines.append("---")
    return "\n".join(lines)


def wiki(relative, label):
    target = "knowledge/_generated/" + (relative[:-3] if relative.endswith(".md") else relative)
    return "[[{}|{}]]".format(target, str(label).replace("|", "／").replace("]", "）"))


def source_link(note_relative, source):
    target = os.path.relpath(source, start=(GENERATED / note_relative).parent).replace("\\", "/")
    return "[查看源码]({})".format(quote(target, safe="/-._~"))


def table_text(value):
    return str(value).replace("|", "／").replace("\n", " ")


def render_production(tool, workflows):
    rel = "正式工具/{}.md".format(tool["tool_id"])
    schema = tool["schema"] if isinstance(tool["schema"], dict) else {}
    props = schema.get("properties", {})
    required = set(schema.get("required", []))
    lines = [
        header("production-tool", tool_id=tool["tool_id"], domain=tool["domain"],
               version=tool["version"], registered=tool["registered"]),
        "# " + tool["name"],
        "",
        tool["description"] or "暂无描述。",
        "",
        "- 工具 ID：{}".format(tool["tool_id"]),
        "- 领域：{}".format(wiki("领域/{}.md".format(tool["domain"]), DOMAIN_NAMES.get(tool["domain"], tool["domain"]))),
        "- 状态：{}".format("已注册，可通过统一 API 调用" if tool["registered"] else "代码存在，但未列入 ALL_TOOL_CLASSES"),
        "- 主实现：{}".format(source_link(rel, tool["source"])),
        "- 代码文件：{} 个，约 {:.1f} KiB".format(len(tool["source_files"]), code_size(tool["source_files"]) / 1024),
        "",
        "## API 参数",
        "",
        "| 参数 | 类型 | 必填 | 默认值 | 描述 |",
        "| --- | --- | --- | --- | --- |",
    ]
    if isinstance(props, dict):
        for name, detail in props.items():
            detail = detail if isinstance(detail, dict) else {}
            default = detail.get("default", "—")
            lines.append("| {} | {} | {} | {} | {} |".format(
                table_text(name), table_text(detail.get("type", "未声明")),
                "是" if name in required else "否", table_text(default),
                table_text(detail.get("description", ""))))
    if not isinstance(props, dict) or not props:
        lines.append("| — | — | — | — | 尚无静态参数描述 |")
    lines += [
        "",
        "调用入口：maya_toolkit.execute_tool(\"{}\", arguments={{...}}, dry_run=True/False)。".format(tool["tool_id"]),
        "",
        "## 共享底层代码",
        "",
    ]
    if tool["core_dependencies"]:
        for module in tool["core_dependencies"]:
            lines.append("- " + wiki("代码模块/core--{}.md".format(module), "core." + module))
    else:
        lines.append("未从静态 import 中识别出直接的 core 模块依赖。")
    lines += ["", "## 框架依赖", ""]
    if tool["framework_dependencies"]:
        for module in tool["framework_dependencies"]:
            lines.append("- " + wiki("代码模块/framework--{}.md".format(module), "framework." + module))
    else:
        lines.append("未从静态 import 中识别出直接的 framework 模块依赖。")
    lines += ["", "## 进一步说明", ""]
    override = DOC_OVERRIDES.get(tool["tool_id"])
    if override and (ROOT / override).exists():
        lines.append("- " + source_link(rel, ROOT / override).replace("查看源码", "专项使用说明"))
    lines.append("- " + source_link(rel, ROOT / "docs" / "llm_tools_cheatsheet.md").replace("查看源码", "API 速查"))
    linked = [item for item in workflows if tool["tool_id"] in (item["from"], item["to"])]
    lines += ["", "## 已验证的功能组合", ""]
    if linked:
        for item in linked:
            other = item["to"] if item["from"] == tool["tool_id"] else item["from"]
            direction = "后续" if item["from"] == tool["tool_id"] else "前置"
            lines.append("- {}：{}。{}".format(
                direction, wiki("正式工具/{}.md".format(other), other), item["reason"]))
    else:
        lines.append("暂无经 Maya 直验并登记的跨工具调用链。")
    lines += [
        "",
        "> 此页从代码元数据生成。Maya 实测结果、实际副作用和可靠的工具组合关系，应在专项知识说明中补充；不能仅由 import 推断。",
        "",
    ]
    return "\n".join(lines)


def render_staging(tool):
    rel = "待整理/{}.md".format(tool["slug"])
    lines = [
        header("staging-tool", status="staging", category=tool["category"],
               inventory_indexed=tool["indexed"], api_ready=False),
        "# " + tool["name"],
        "",
        tool["description"],
        "",
        "- 分类：{}".format(wiki("待整理分类/{}.md".format(tool["category"]), tool["category"])),
        "- 源目录：{}".format(tool["key"]),
        "- 代码文件：{} 个，约 {:.1f} KiB".format(len(tool["source_files"]), code_size(tool["source_files"]) / 1024),
        "- 原清单登记：{}".format("是" if tool["indexed"] else "否，尚需核对名称与描述"),
    ]
    if tool["main_source"]:
        lines.append("- 主入口：" + source_link(rel, tool["main_source"]))
    lines += [
        "",
        "> 待整理状态不代表已通过 Maya 直验，也不代表具备统一 API。转正须遵循 [[DEVELOPMENT_SPEC|开发规范]]。",
        "",
    ]
    return "\n".join(lines)


def render_module(module, users):
    rel = "代码模块/{}--{}.md".format(module["layer"], module["name"])
    lines = [
        header("code-module", layer=module["layer"], module=module["name"]),
        "# {}.{}".format(module["layer"], module["name"]),
        "",
        "- 源码：" + source_link(rel, module["path"]),
        "- 顶层类与函数：{}".format("、".join(module["symbols"]) if module["symbols"] else "无公开顶层符号"),
        "",
        "## 正式工具的直接引用",
        "",
    ]
    if users:
        lines.extend("- " + wiki("正式工具/{}.md".format(tool["tool_id"]), tool["name"]) for tool in users)
    else:
        lines.append("当前未从正式工具的静态 import 中识别出直接引用。")
    lines.append("")
    return "\n".join(lines)


def render_dashboard(production, staging, inventory, modules, workflows):
    registered = [tool for tool in production if tool["registered"]]
    indexed = sum(tool["indexed"] for tool in staging)
    core_uses = Counter(module for tool in registered for module in tool["core_dependencies"])
    shared_pairs = sum(
        bool(set(left["core_dependencies"]) & set(right["core_dependencies"]))
        for index, left in enumerate(registered)
        for right in registered[index + 1:]
    )
    possible_pairs = len(registered) * (len(registered) - 1) // 2
    populated_domains = {tool["domain"] for tool in registered}
    unindexed = [tool for tool in staging if not tool["indexed"]]
    lines = [
        header("project-dashboard"),
        "# 项目规模与能力总览",
        "",
        "> 此页由仓库目录、正式工具静态元数据与待整理库清单生成，不执行 Maya 代码。",
        "",
        "| 指标 | 当前值 | 解释 |",
        "| --- | ---: | --- |",
        "| 正式工具目录 | {} | 其中 {} 项列入 ALL_TOOL_CLASSES |".format(len(production), len(registered)),
        "| 待整理工具目录 | {} | 实际扫描所得，不与正式工具去重 |".format(len(staging)),
        "| 待整理清单登记 | {} | 清单表格共 {} 项 |".format(indexed, len(inventory)),
        "| 待整理未登记目录 | {} | 需补清单，不代表不可用 |".format(len(unindexed)),
        "| 正式业务领域 | {} / {} | 至少有一项已注册工具的领域 |".format(len(populated_domains), len(DOMAIN_NAMES)),
        "| core 模块 | {} | 公共底层源码模块 |".format(sum(m["layer"] == "core" for m in modules)),
        "| 被多个正式工具直接引用的 core 模块 | {} | 结构复用指标，不代表功能可串联 |".format(sum(count >= 2 for count in core_uses.values())),
        "| 共享 core 的正式工具对 | {} / {} | 直接代码依赖形成的结构关联 |".format(shared_pairs, possible_pairs),
        "| 已验证功能组合 | {} | 需在 knowledge/relations.json 登记验证依据 |".format(len(workflows)),
        "",
        "## 按正式业务领域",
        "",
        "| 领域 | 正式工具数 |",
        "| --- | ---: |",
    ]
    for domain, name in DOMAIN_NAMES.items():
        count = sum(tool["registered"] and tool["domain"] == domain for tool in production)
        lines.append("| {} | {} |".format(wiki("领域/{}.md".format(domain), name), count))
    lines += ["", "## 按待整理分类", "", "| 分类 | 目录数 |", "| --- | ---: |"]
    for category in sorted({tool["category"] for tool in staging}):
        count = sum(tool["category"] == category for tool in staging)
        lines.append("| {} | {} |".format(wiki("待整理分类/{}.md".format(category), category), count))
    lines += ["", "## 公共模块复用", "", "| core 模块 | 直接引用的正式工具数 |", "| --- | ---: |"]
    for module, count in sorted(core_uses.items(), key=lambda item: (-item[1], item[0])):
        lines.append("| {} | {} |".format(wiki("代码模块/core--{}.md".format(module), module), count))
    if unindexed:
        lines += ["", "## 待整理目录与清单差异", ""]
        lines.extend("- " + wiki("待整理/{}.md".format(tool["slug"]), tool["key"]) for tool in unindexed)
    lines += [
        "",
        "## 能力判断边界",
        "",
        "- 已注册工具有统一调度入口；待整理目录不能计入可调用 API。",
        "- 静态 import 只说明代码依赖，不能证明 Maya 运行结果或工具之间可直接串联。",
        "- 经过验证的功能组合需要在知识卡或关系清单中单独记录。",
        "",
    ]
    return "\n".join(lines)


def render_relations(production, workflows):
    pairs = []
    for index, left in enumerate(production):
        if not left["registered"]:
            continue
        for right in production[index + 1:]:
            if not right["registered"]:
                continue
            shared = sorted(set(left["core_dependencies"]) & set(right["core_dependencies"]))
            if shared:
                pairs.append((left, right, shared))
    lines = [
        header("structural-relations"),
        "# 工具与公共代码关联",
        "",
        "> 下表来自 Python import 的静态分析，只表示共享底层代码；不是经过验证的功能调用链。",
        "",
        "| 工具 A | 工具 B | 共同引用的 core 模块 |",
        "| --- | --- | --- |",
    ]
    for left, right, shared in sorted(pairs, key=lambda item: (-len(item[2]), item[0]["tool_id"], item[1]["tool_id"])):
        lines.append("| {} | {} | {} |".format(
            wiki("正式工具/{}.md".format(left["tool_id"]), left["tool_id"]),
            wiki("正式工具/{}.md".format(right["tool_id"]), right["tool_id"]),
            "、".join(wiki("代码模块/core--{}.md".format(name), name) for name in shared)))
    if not pairs:
        lines.append("| — | — | 尚无共同引用 |")
    lines += [
        "",
        "## 已确认的功能组合",
        "",
    ]
    if workflows:
        lines += [
            "| 前置工具 | 后续工具 | 组合理由 | 验证说明 |",
            "| --- | --- | --- | --- |",
        ]
        for item in workflows:
            evidence = item["evidence"]
            evidence_link = "[说明]({})".format(quote(os.path.relpath(
                ROOT / evidence, start=GENERATED).replace("\\", "/"), safe="/-._~")) if evidence and (ROOT / evidence).is_file() else "—"
            lines.append("| {} | {} | {} | {} |".format(
                wiki("正式工具/{}.md".format(item["from"]), item["from"]),
                wiki("正式工具/{}.md".format(item["to"]), item["to"]),
                table_text(item["reason"]), evidence_link))
    else:
        lines.append("目前没有经 Maya 直验并登记的跨工具调用链。后续可按 [知识卡模板](../../docs/tools/_tool_knowledge_template.md) 补充输入输出衔接，再把已确认关系写入 knowledge/relations.json。")
    lines.append("")
    return "\n".join(lines)


def render_map(production):
    lines = [
        header("project-map"),
        "# 项目结构图",
        "",
        "```mermaid",
        "flowchart LR",
    ]
    for domain, name in DOMAIN_NAMES.items():
        lines.append('    domain_{}["{}"]'.format(domain, name))
    for tool in production:
        node_id = "tool_" + re.sub(r"\W", "_", tool["tool_id"])
        lines.append('    {}["{}"]'.format(node_id, tool["tool_id"]))
        lines.append("    domain_{} --> {}".format(tool["domain"], node_id))
        for core in tool["core_dependencies"]:
            lines.append('    core_{}["core.{}"]'.format(core, core))
            lines.append("    {} --> core_{}".format(node_id, core))
    lines += [
        "```",
        "",
        "箭头表示正式工具所属领域及代码中的直接公共模块引用。它不表示工具执行顺序。",
        "",
    ]
    return "\n".join(lines)


def sync():
    production = production_tools()
    staging, inventory = staging_tools()
    modules = module_notes()
    workflows = verified_workflows(production)
    expected = {}

    for tool in production:
        expected["正式工具/{}.md".format(tool["tool_id"])] = render_production(tool, workflows)
    for tool in staging:
        expected["待整理/{}.md".format(tool["slug"])] = render_staging(tool)
    for module in modules:
        users = [
            tool for tool in production
            if module["layer"] in ("core", "framework")
            and module["name"] in tool[module["layer"] + "_dependencies"]
        ]
        expected["代码模块/{}--{}.md".format(module["layer"], module["name"])] = render_module(module, users)
    for domain, name in DOMAIN_NAMES.items():
        tools = [tool for tool in production if tool["domain"] == domain]
        lines = [header("domain", domain=domain), "# " + name, "", "## 正式工具", ""]
        lines.extend("- " + wiki("正式工具/{}.md".format(tool["tool_id"]), tool["name"]) for tool in tools)
        if not tools:
            lines.append("暂无已转正工具。")
        expected["领域/{}.md".format(domain)] = "\n".join(lines) + "\n"
    for category in sorted({tool["category"] for tool in staging}):
        tools = [tool for tool in staging if tool["category"] == category]
        lines = [header("staging-category", category=category), "# " + category, "", "## 待整理工具", ""]
        lines.extend("- " + wiki("待整理/{}.md".format(tool["slug"]), tool["name"]) for tool in tools)
        expected["待整理分类/{}.md".format(category)] = "\n".join(lines) + "\n"

    expected["规模评估.md"] = render_dashboard(production, staging, inventory, modules, workflows)
    expected["能力关联.md"] = render_relations(production, workflows)
    expected["项目地图.md"] = render_map(production)
    expected["总览.md"] = "\n".join([
        header("knowledge-home"),
        "# Maya Tools Box 知识库",
        "",
        "- " + wiki("规模评估.md", "项目规模与能力总览"),
        "- " + wiki("能力关联.md", "工具与公共代码关联"),
        "- " + wiki("项目地图.md", "项目结构图"),
        "",
        "## 项目规范",
        "",
        "- [[README|项目说明]]",
        "- [[AGENTS|代理开发规则]]",
        "- [[DEVELOPMENT_SPEC|工具转正规范]]",
        "- [[docs/llm_tools_cheatsheet|API 速查]]",
        "",
        "生成页以代码和目录为准。任何工具的实际效果与跨工具组合仍需 Maya 直验。",
        "",
    ])

    changed = 0
    expected_paths = set()
    for relative, body in expected.items():
        path = GENERATED / relative
        expected_paths.add(path)
        body = body.rstrip() + "\n"
        frontmatter_end = body.find("\n---\n", 4)
        if frontmatter_end < 0:
            raise ValueError("Generated page lacks YAML frontmatter: {}".format(relative))
        insert_at = frontmatter_end + len("\n---\n")
        content = body[:insert_at] + "\n" + MARKER + "\n" + body[insert_at:]
        path.parent.mkdir(parents=True, exist_ok=True)
        if not path.exists() or text_file(path) != content:
            path.write_text(content, encoding="utf-8")
            changed += 1
    if GENERATED.exists():
        for path in GENERATED.rglob("*.md"):
            if path not in expected_paths and MARKER in text_file(path)[:512]:
                path.unlink()
                changed += 1
    return {
        "production": len(production),
        "registered": sum(tool["registered"] for tool in production),
        "staging": len(staging),
        "inventory": len(inventory),
        "pages": len(expected),
        "changed": changed,
    }


def watched_files():
    paths = [ROOT / name for name in ("README.md", "AGENTS.md", "DEVELOPMENT_SPEC.md",
                                     "knowledge/relations.json")]
    for folder in ("maya_toolkit", "tools_staging_pool", "docs", "tests"):
        base = ROOT / folder
        if not base.exists():
            continue
        for path in base.rglob("*"):
            if path.is_file() and path.suffix.lower() in WATCH_SUFFIXES:
                if not any(part in IGNORED_DIRS for part in path.relative_to(base).parts):
                    paths.append(path)
    return sorted(set(path for path in paths if path.exists()))


def snapshot():
    return tuple((str(path.relative_to(ROOT)), path.stat().st_mtime_ns, path.stat().st_size)
                 for path in watched_files())


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--watch", action="store_true", help="Regenerate after source file changes")
    parser.add_argument("--interval", type=float, default=2.0, help="Watch polling interval in seconds")
    args = parser.parse_args()
    last = None
    while True:
        current = snapshot()
        if current != last:
            try:
                report = sync()
                print(json.dumps(report, ensure_ascii=False), flush=True)
            except Exception as exc:
                if not args.watch:
                    raise
                print("知识库同步失败: {}".format(exc), file=sys.stderr, flush=True)
            last = snapshot()
        if not args.watch:
            break
        try:
            time.sleep(max(args.interval, 0.5))
        except KeyboardInterrupt:
            break


if __name__ == "__main__":
    main()
