/* dofControl.mel V1.0

This script may be freely distributed. Modify at your own risk.

Author: Dirk Bialluch <DirkBi@Software2000.de> <http://dirk-bialluch.mayaring.com>

Creation date:	12.01.2000
Last update:	13.01.2000

Description
	This script creates a DOF control (polyCube) for selected cameras.

	TranslateZ = focus distance
	ScaleZ = focus range
	
NOTE
	The polyCube will not appear in the rendered image. To hide the cube
	in shaded view use 'toggle template'.
*/

//
// Main
//

global proc dofControl ()
{
	string $objList[] = `ls -sl -ca -dag`;
	print $objList;

	if ( !size( $objList ) )
	{
		print "No camera node(s) selected\n";
		return;
	}

	// iterate through list of camera shapes
	for ( $objCnt = 0; $objCnt < size( $objList ); $objCnt++ )
	{
		// get cameraShape transform node
		string $camTransNode[] = `listRelatives -parent $objList[$objCnt]`;
		print $camTransNode[0];

		// get current settings from camera
		float $oldFocusDistance = `getAttr ( $objList[$objCnt] + ".focusDistance" )`;
		float $oldFStop = `getAttr ( $objList[$objCnt] + ".fStop" )`;

		// create polyCube for DOF area display
		string $cube[] = `polyCube -sx 1 -sy 1 -sz 1 -ch off`;
		$cube[0] = `rename $cube[0] ( $camTransNode[0] + "dofArea#" )`;
		setAttr -lock true ( $cube[0] + ".tx" );
		setAttr -lock true ( $cube[0] + ".ty" );
		setAttr -lock true ( $cube[0] + ".rx" );
		setAttr -lock true ( $cube[0] + ".ry" );
		setAttr -lock true ( $cube[0] + ".rz" );
		setAttr ( $cube[0] + ".tz" ) ( -$oldFocusDistance );
		setAttr ( $cube[0] + ".sz" ) $oldFStop;
		setAttr ( $cube[0] + ".castsShadows" ) 0;
		setAttr ( $cube[0] + ".primaryVisibility" ) 0;
		setAttr ( $cube[0] + ".visibleInReflections" ) 0;
		setAttr ( $cube[0] + ".visibleInRefractions" ) 0;

		// parent polyCube to camera
		parent -r $cube[0] $camTransNode[0];

		// create 'reverse' node
		string $revNode = `createNode "reverse"`;

		// create 'add' node
		string $addNode = `createNode "addDoubleLinear"`;
		setAttr ( $addNode + ".input2" ) 1;

		// make connections
		connectAttr -f ( $cube[0] + ".translateZ" ) ( $addNode + ".input1" );
		connectAttr -f ( $addNode + ".output" ) ( $revNode + ".inputX" );
		connectAttr -f ( $revNode + ".outputX" ) ( $objList[$objCnt] + ".focusDistance" );

		connectAttr -f ( $cube[0] + ".scaleZ" ) ( $objList[$objCnt] + ".fStop" );

		connectAttr -f ( $cube[0] + ".tz" ) ( $cube[0] + ".sx" );
		connectAttr -f ( $cube[0] + ".tz" ) ( $cube[0] + ".sy" );
	}
}

// end of script
