# uncompyle6 version 3.8.0
# Python bytecode 2.7 (62211)
# Decompiled from: Python 3.10.2 (tags/v3.10.2:a58ebcc, Jan 17 2022, 14:12:15) [MSC v.1929 64 bit (AMD64)]
# Embedded file name: F:/Maya_Projects\sat\mainWindow.py
# Compiled at: 2016-11-26 19:45:40
from .Qt import QtCore, QtWidgets, QtGui

class Ui_MainWindow(object):

    def setupUi(self, MainWindow):
        MainWindow.setObjectName('MainWindow')
        MainWindow.resize(458, 249)
        MainWindow.setDocumentMode(False)
        MainWindow.setDockOptions(QtWidgets.QMainWindow.AllowTabbedDocks | QtWidgets.QMainWindow.AnimatedDocks)
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName('centralwidget')
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout.setObjectName('horizontalLayout')
        self.geo_groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.geo_groupBox.setEnabled(True)
        self.geo_groupBox.setObjectName('geo_groupBox')
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.geo_groupBox)
        self.verticalLayout_4.setObjectName('verticalLayout_4')
        self.geo_listWidget = QtWidgets.QListWidget(self.geo_groupBox)
        self.geo_listWidget.setAlternatingRowColors(True)
        self.geo_listWidget.setObjectName('geo_listWidget')
        self.verticalLayout_4.addWidget(self.geo_listWidget)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName('verticalLayout')
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(2)
        self.horizontalLayout_3.setObjectName('horizontalLayout_3')
        self.add_btn = QtWidgets.QPushButton(self.geo_groupBox)
        self.add_btn.setEnabled(True)
        self.add_btn.setMinimumSize(QtCore.QSize(60, 0))
        self.add_btn.setMaximumSize(QtCore.QSize(60, 16777215))
        self.add_btn.setToolTip('')
        self.add_btn.setCheckable(False)
        self.add_btn.setObjectName('add_btn')
        self.horizontalLayout_3.addWidget(self.add_btn)
        self.pick_btn = QtWidgets.QPushButton(self.geo_groupBox)
        self.pick_btn.setEnabled(True)
        self.pick_btn.setMinimumSize(QtCore.QSize(60, 0))
        self.pick_btn.setMaximumSize(QtCore.QSize(60, 16777215))
        self.pick_btn.setToolTip('')
        self.pick_btn.setCheckable(False)
        self.pick_btn.setObjectName('pick_btn')
        self.horizontalLayout_3.addWidget(self.pick_btn)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.remove_btn = QtWidgets.QPushButton(self.geo_groupBox)
        self.remove_btn.setMinimumSize(QtCore.QSize(60, 0))
        self.remove_btn.setMaximumSize(QtCore.QSize(60, 16777215))
        self.remove_btn.setObjectName('remove_btn')
        self.horizontalLayout_3.addWidget(self.remove_btn)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.verticalLayout_4.addLayout(self.verticalLayout)
        self.horizontalLayout.addWidget(self.geo_groupBox)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setContentsMargins(-1, 0, -1, 0)
        self.verticalLayout_8.setObjectName('verticalLayout_8')
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setMaximumSize(QtCore.QSize(220, 95))
        self.groupBox_3.setObjectName('groupBox_3')
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setObjectName('verticalLayout_9')
        self.frame_3 = QtWidgets.QFrame(self.groupBox_3)
        self.frame_3.setMinimumSize(QtCore.QSize(215, 100))
        self.frame_3.setMaximumSize(QtCore.QSize(210, 75))
        self.frame_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_3.setObjectName('frame_3')
        self.deleteKey_btn = QtWidgets.QPushButton(self.frame_3)
        self.deleteKey_btn.setGeometry(QtCore.QRect(110, 0, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.deleteKey_btn.setFont(font)
        self.deleteKey_btn.setObjectName('deleteKey_btn')
        self.key_btn = QtWidgets.QPushButton(self.frame_3)
        self.key_btn.setGeometry(QtCore.QRect(5, 0, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.key_btn.setFont(font)
        self.key_btn.setObjectName('key_btn')
        self.keyData_label = QtWidgets.QLabel(self.frame_3)
        self.keyData_label.setGeometry(QtCore.QRect(75, 50, 61, 20))
        self.keyData_label.setAlignment(QtCore.Qt.AlignCenter)
        self.keyData_label.setObjectName('keyData_label')
        self.prevKey_btn = QtWidgets.QPushButton(self.frame_3)
        self.prevKey_btn.setGeometry(QtCore.QRect(5, 45, 71, 26))
        self.prevKey_btn.setObjectName('prevKey_btn')
        self.nextKey_btn = QtWidgets.QPushButton(self.frame_3)
        self.nextKey_btn.setGeometry(QtCore.QRect(140, 45, 71, 26))
        self.nextKey_btn.setObjectName('nextKey_btn')
        self.verticalLayout_9.addWidget(self.frame_3)
        self.verticalLayout_8.addWidget(self.groupBox_3)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem1)
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox_4.setMaximumSize(QtCore.QSize(220, 16777215))
        self.groupBox_4.setObjectName('groupBox_4')
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_10.setSpacing(0)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setObjectName('verticalLayout_10')
        self.frame_7 = QtWidgets.QFrame(self.groupBox_4)
        self.frame_7.setMinimumSize(QtCore.QSize(215, 90))
        self.frame_7.setMaximumSize(QtCore.QSize(200, 90))
        self.frame_7.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_7.setObjectName('frame_7')
        self.brush_btn = QtWidgets.QPushButton(self.frame_7)
        self.brush_btn.setEnabled(False)
        self.brush_btn.setGeometry(QtCore.QRect(5, 55, 41, 31))
        self.brush_btn.setObjectName('brush_btn')
        self.sculpt_btn = QtWidgets.QPushButton(self.frame_7)
        self.sculpt_btn.setGeometry(QtCore.QRect(5, 0, 206, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(50)
        font.setItalic(False)
        font.setUnderline(False)
        font.setBold(False)
        self.sculpt_btn.setFont(font)
        self.sculpt_btn.setIconSize(QtCore.QSize(32, 32))
        self.sculpt_btn.setCheckable(True)
        self.sculpt_btn.setObjectName('sculpt_btn')
        self.points_btn = QtWidgets.QPushButton(self.frame_7)
        self.points_btn.setEnabled(False)
        self.points_btn.setGeometry(QtCore.QRect(95, 55, 41, 31))
        self.points_btn.setObjectName('points_btn')
        self.resetShape_btn = QtWidgets.QPushButton(self.frame_7)
        self.resetShape_btn.setEnabled(False)
        self.resetShape_btn.setGeometry(QtCore.QRect(140, 55, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.resetShape_btn.setFont(font)
        self.resetShape_btn.setObjectName('resetShape_btn')
        self.shapesBrush_btn = QtWidgets.QPushButton(self.frame_7)
        self.shapesBrush_btn.setEnabled(False)
        self.shapesBrush_btn.setGeometry(QtCore.QRect(50, 55, 41, 31))
        self.shapesBrush_btn.setObjectName('shapesBrush_btn')
        self.verticalLayout_10.addWidget(self.frame_7)
        self.verticalLayout_8.addWidget(self.groupBox_4)
        self.verticalLayout_8.setStretch(1, 1)
        self.horizontalLayout.addLayout(self.verticalLayout_8)
        self.horizontalLayout.setStretch(0, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 458, 18))
        self.menubar.setObjectName('menubar')
        self.menuAdd = QtWidgets.QMenu(self.menubar)
        self.menuAdd.setObjectName('menuAdd')
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName('menuHelp')
        self.menuAnimation = QtWidgets.QMenu(self.menubar)
        self.menuAnimation.setObjectName('menuAnimation')
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName('menuEdit')
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setEnabled(True)
        self.statusbar.setObjectName('statusbar')
        MainWindow.setStatusBar(self.statusbar)
        self.actionAdd = QtWidgets.QAction(MainWindow)
        self.actionAdd.setEnabled(True)
        self.actionAdd.setVisible(True)
        self.actionAdd.setObjectName('actionAdd')
        self.actionAdd_Selected_Geometry = QtWidgets.QAction(MainWindow)
        self.actionAdd_Selected_Geometry.setObjectName('actionAdd_Selected_Geometry')
        self.actionVideoTutorial = QtWidgets.QAction(MainWindow)
        self.actionVideoTutorial.setEnabled(False)
        self.actionVideoTutorial.setObjectName('actionVideoTutorial')
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName('actionAbout')
        self.actionRemove = QtWidgets.QAction(MainWindow)
        self.actionRemove.setObjectName('actionRemove')
        self.actionRemove_All = QtWidgets.QAction(MainWindow)
        self.actionRemove_All.setEnabled(True)
        self.actionRemove_All.setObjectName('actionRemove_All')
        self.actionSet_Key = QtWidgets.QAction(MainWindow)
        self.actionSet_Key.setObjectName('actionSet_Key')
        self.actionDelete_Key = QtWidgets.QAction(MainWindow)
        self.actionDelete_Key.setObjectName('actionDelete_Key')
        self.actionDelete_All_Keys = QtWidgets.QAction(MainWindow)
        self.actionDelete_All_Keys.setEnabled(True)
        self.actionDelete_All_Keys.setObjectName('actionDelete_All_Keys')
        self.actionSelect_Curves = QtWidgets.QAction(MainWindow)
        self.actionSelect_Curves.setObjectName('actionSelect_Curves')
        self.actionEdit_Mode = QtWidgets.QAction(MainWindow)
        self.actionEdit_Mode.setObjectName('actionEdit_Mode')
        self.actionBrush_Tool = QtWidgets.QAction(MainWindow)
        self.actionBrush_Tool.setObjectName('actionBrush_Tool')
        self.actionSelect_Vertexes_tool = QtWidgets.QAction(MainWindow)
        self.actionSelect_Vertexes_tool.setObjectName('actionSelect_Vertexes_tool')
        self.actionSelect_Object = QtWidgets.QAction(MainWindow)
        self.actionSelect_Object.setObjectName('actionSelect_Object')
        self.actionReset_Shape = QtWidgets.QAction(MainWindow)
        self.actionReset_Shape.setObjectName('actionReset_Shape')
        self.actionBrush_Tool_Window = QtWidgets.QAction(MainWindow)
        self.actionBrush_Tool_Window.setEnabled(True)
        self.actionBrush_Tool_Window.setObjectName('actionBrush_Tool_Window')
        self.actionHome_Page = QtWidgets.QAction(MainWindow)
        self.actionHome_Page.setObjectName('actionHome_Page')
        self.actionPick = QtWidgets.QAction(MainWindow)
        self.actionPick.setObjectName('actionPick')
        self.actionPrevious_Key = QtWidgets.QAction(MainWindow)
        self.actionPrevious_Key.setObjectName('actionPrevious_Key')
        self.actionNext_Key = QtWidgets.QAction(MainWindow)
        self.actionNext_Key.setObjectName('actionNext_Key')
        self.actionEdit_Mode_2 = QtWidgets.QAction(MainWindow)
        self.actionEdit_Mode_2.setObjectName('actionEdit_Mode_2')
        self.actionTutorial = QtWidgets.QAction(MainWindow)
        self.actionTutorial.setObjectName('actionTutorial')
        self.actionUse_Artisan_Tool = QtWidgets.QAction(MainWindow)
        self.actionUse_Artisan_Tool.setObjectName('actionUse_Artisan_Tool')
        self.actionUse_ShapesBrush_plugin = QtWidgets.QAction(MainWindow)
        self.actionUse_ShapesBrush_plugin.setObjectName('actionUse_ShapesBrush_plugin')
        self.actionUse_Components = QtWidgets.QAction(MainWindow)
        self.actionUse_Components.setObjectName('actionUse_Components')
        self.actionReset_Shape_to_Default = QtWidgets.QAction(MainWindow)
        self.actionReset_Shape_to_Default.setObjectName('actionReset_Shape_to_Default')
        self.menuAdd.addAction(self.actionAdd)
        self.menuAdd.addAction(self.actionPick)
        self.menuAdd.addAction(self.actionRemove)
        self.menuAdd.addAction(self.actionRemove_All)
        self.menuHelp.addAction(self.actionHome_Page)
        self.menuHelp.addAction(self.actionTutorial)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionAbout)
        self.menuAnimation.addAction(self.actionSet_Key)
        self.menuAnimation.addAction(self.actionDelete_Key)
        self.menuAnimation.addAction(self.actionDelete_All_Keys)
        self.menuAnimation.addSeparator()
        self.menuAnimation.addAction(self.actionPrevious_Key)
        self.menuAnimation.addAction(self.actionNext_Key)
        self.menuEdit.addAction(self.actionBrush_Tool_Window)
        self.menuEdit.addAction(self.actionEdit_Mode_2)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionUse_Artisan_Tool)
        self.menuEdit.addAction(self.actionUse_ShapesBrush_plugin)
        self.menuEdit.addAction(self.actionUse_Components)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionReset_Shape_to_Default)
        self.menubar.addAction(self.menuAdd.menuAction())
        self.menubar.addAction(self.menuAnimation.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate('MainWindow', 'Shape Animation Tool 2.0', None))
        self.geo_groupBox.setTitle(QtWidgets.QApplication.translate('MainWindow', 'Select Geometry', None))
        self.add_btn.setText(QtWidgets.QApplication.translate('MainWindow', 'Add', None))
        self.pick_btn.setText(QtWidgets.QApplication.translate('MainWindow', 'Pick', None))
        self.remove_btn.setText(QtWidgets.QApplication.translate('MainWindow', 'Remove', None))
        self.groupBox_3.setTitle(QtWidgets.QApplication.translate('MainWindow', 'Set Key', None))
        self.deleteKey_btn.setText(QtWidgets.QApplication.translate('MainWindow', 'Del Key', None))
        self.key_btn.setText(QtWidgets.QApplication.translate('MainWindow', 'Key', None))
        self.keyData_label.setText(QtWidgets.QApplication.translate('MainWindow', '  - / -', None))
        self.prevKey_btn.setText(QtWidgets.QApplication.translate('MainWindow', '<', None))
        self.nextKey_btn.setText(QtWidgets.QApplication.translate('MainWindow', '>', None))
        self.groupBox_4.setTitle(QtWidgets.QApplication.translate('MainWindow', 'Edit Shape', None))
        self.brush_btn.setText(QtWidgets.QApplication.translate('MainWindow', 'Sculpt', None))
        self.sculpt_btn.setText(QtWidgets.QApplication.translate('MainWindow', 'Edit', None))
        self.points_btn.setText(QtWidgets.QApplication.translate('MainWindow', 'Vertex', None))
        self.resetShape_btn.setText(QtWidgets.QApplication.translate('MainWindow', 'Reset', None))
        self.shapesBrush_btn.setText(QtWidgets.QApplication.translate('MainWindow', 'SBrush', None))
        self.menuAdd.setTitle(QtWidgets.QApplication.translate('MainWindow', 'Geometry', None))
        self.menuHelp.setTitle(QtWidgets.QApplication.translate('MainWindow', 'Help', None))
        self.menuAnimation.setTitle(QtWidgets.QApplication.translate('MainWindow', 'Animation', None))
        self.menuEdit.setTitle(QtWidgets.QApplication.translate('MainWindow', 'Sculpt', None))
        self.actionAdd.setText(QtWidgets.QApplication.translate('MainWindow', 'Add', None))
        self.actionAdd.setToolTip(QtWidgets.QApplication.translate('MainWindow', 'Add Character or Prop Geometry', None))
        self.actionAdd_Selected_Geometry.setText(QtWidgets.QApplication.translate('MainWindow', 'Add Selected Geometry', None))
        self.actionVideoTutorial.setText(QtWidgets.QApplication.translate('MainWindow', 'Tutorial (Rus)', None))
        self.actionAbout.setText(QtWidgets.QApplication.translate('MainWindow', 'About', None))
        self.actionRemove.setText(QtWidgets.QApplication.translate('MainWindow', 'Remove', None))
        self.actionRemove_All.setText(QtWidgets.QApplication.translate('MainWindow', 'Remove All', None))
        self.actionSet_Key.setText(QtWidgets.QApplication.translate('MainWindow', 'Set Key', None))
        self.actionDelete_Key.setText(QtWidgets.QApplication.translate('MainWindow', 'Delete Key', None))
        self.actionDelete_All_Keys.setText(QtWidgets.QApplication.translate('MainWindow', 'Delete All Keys', None))
        self.actionSelect_Curves.setText(QtWidgets.QApplication.translate('MainWindow', 'Select Curves', None))
        self.actionEdit_Mode.setText(QtWidgets.QApplication.translate('MainWindow', 'Edit Mode', None))
        self.actionBrush_Tool.setText(QtWidgets.QApplication.translate('MainWindow', 'Brush', None))
        self.actionSelect_Vertexes_tool.setText(QtWidgets.QApplication.translate('MainWindow', 'Select Vertexes', None))
        self.actionSelect_Object.setText(QtWidgets.QApplication.translate('MainWindow', 'Select Object', None))
        self.actionReset_Shape.setText(QtWidgets.QApplication.translate('MainWindow', 'Reset Shape', None))
        self.actionBrush_Tool_Window.setText(QtWidgets.QApplication.translate('MainWindow', 'Brush Tool Options ..', None))
        self.actionHome_Page.setText(QtWidgets.QApplication.translate('MainWindow', 'Home Page', None))
        self.actionPick.setText(QtWidgets.QApplication.translate('MainWindow', 'Pick Tool', None))
        self.actionPrevious_Key.setText(QtWidgets.QApplication.translate('MainWindow', 'Go To Previous Key', None))
        self.actionNext_Key.setText(QtWidgets.QApplication.translate('MainWindow', 'Go To Next Key', None))
        self.actionEdit_Mode_2.setText(QtWidgets.QApplication.translate('MainWindow', 'Edit Mode', None))
        self.actionTutorial.setText(QtWidgets.QApplication.translate('MainWindow', 'Tutorial', None))
        self.actionUse_Artisan_Tool.setText(QtWidgets.QApplication.translate('MainWindow', 'Use Artisan Tool', None))
        self.actionUse_ShapesBrush_plugin.setText(QtWidgets.QApplication.translate('MainWindow', 'Use ShapesBrush', None))
        self.actionUse_Components.setText(QtWidgets.QApplication.translate('MainWindow', 'Edit Components', None))
        self.actionReset_Shape_to_Default.setText(QtWidgets.QApplication.translate('MainWindow', 'Reset Shape', None))
        return